-- Agency credit limit (ADR 0024). One limit per agency, in one currency, as integer minor units. No row means no limit is
-- configured and nothing is enforced. The limit is set only by the API after an approved maker-checker request
-- (action agency.credit_limit.set); nothing here moves money or touches a wallet or ledger.
--
-- Integrity beyond Prisma: ISO-4217 shape for the currency, limit >= 0, one row per agency.
-- "updated_by_id" is plain text without a foreign key so history survives user removal.
--
-- Tenant indexes: "tenant_id" leads the non-unique index. The exposure query reads "InventoryHold" by tenant, creator and status,
-- so "InventoryHold_tenant_id_created_by_user_id_status_idx" is added (reviewed: a read-only path, no write amplification beyond
-- one small index on a table that is written once per hold plus status updates).
--
-- The conditional GRANT mirrors earlier migrations (ADR 0013): it is a production privilege change in effect and needs the
-- human decision before this migration is applied to any persistent environment. Without it the API refuses new holds for
-- every agency with a credit-limit lookup failure rather than ignoring the limit (fail closed, ADR 0024).
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP INDEX IF EXISTS "InventoryHold_tenant_id_created_by_user_id_status_idx"; DROP TABLE IF EXISTS "AgencyCreditLimit";

-- CreateTable
CREATE TABLE "AgencyCreditLimit" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "agency_id" TEXT NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "limit_minor" BIGINT NOT NULL,
    "updated_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AgencyCreditLimit_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AgencyCreditLimit_agency_id_key" ON "AgencyCreditLimit"("agency_id");

-- CreateIndex
CREATE INDEX "AgencyCreditLimit_tenant_id_agency_id_idx" ON "AgencyCreditLimit"("tenant_id", "agency_id");

-- CreateIndex
CREATE INDEX "InventoryHold_tenant_id_created_by_user_id_status_idx" ON "InventoryHold"("tenant_id", "created_by_user_id", "status");

-- AddForeignKey
ALTER TABLE "AgencyCreditLimit" ADD CONSTRAINT "AgencyCreditLimit_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgencyCreditLimit" ADD CONSTRAINT "AgencyCreditLimit_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "Agency"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Integrity constraints
ALTER TABLE "AgencyCreditLimit" ADD CONSTRAINT "AgencyCreditLimit_currency_format" CHECK ("currency" ~ '^[A-Z]{3}$'),
  ADD CONSTRAINT "AgencyCreditLimit_limit_non_negative" CHECK ("limit_minor" >= 0);

-- Row-level security: tenant isolation.
ALTER TABLE "AgencyCreditLimit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgencyCreditLimit" FORCE ROW LEVEL SECURITY;
CREATE POLICY "AgencyCreditLimit_tenant_isolation" ON "AgencyCreditLimit" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "AgencyCreditLimit" TO fbeds_api';
  END IF;
END $$;
