-- Supplier extranet membership and private room-note drafts.
-- A membership links an authenticated user to one tenant-owned supplier organization.
-- It does not grant admin supply permissions. A room draft stores a private note only.
-- It does not change Hotel, RoomType, rates, availability, mappings, or publication.
--
-- Tenant indexes: supplier_memberships is listed by (tenant_id, user_id, status)
-- before an organization is chosen, and by (tenant_id, supplier_id) for membership checks.
-- supplier_room_drafts is listed by (tenant_id, supplier_id, hotel_id) and uniquely
-- constrained by (tenant_id, supplier_id, room_type_id).
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP POLICY IF EXISTS "supplier_room_drafts_tenant_supplier_isolation" ON "supplier_room_drafts";
--   DROP POLICY IF EXISTS "supplier_memberships_tenant_isolation" ON "supplier_memberships";
--   DROP TABLE IF EXISTS "supplier_room_drafts";
--   DROP TABLE IF EXISTS "supplier_memberships";
--   DROP TYPE IF EXISTS "SupplierMembershipStatus";
--   DELETE FROM "Permission" WHERE "key" IN (
--     'supplier.extranet.hotels.read',
--     'supplier.extranet.rooms.read',
--     'supplier.extranet.drafts.manage'
--   );
-- Do not drop Supplier, Hotel, RoomType, users, or tenants.

CREATE TYPE "SupplierMembershipStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'REVOKED');

CREATE TABLE "supplier_memberships" (
  "id" TEXT NOT NULL,
  "tenant_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "supplier_id" TEXT NOT NULL,
  "status" "SupplierMembershipStatus" NOT NULL DEFAULT 'ACTIVE',
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "supplier_memberships_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "supplier_memberships_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "supplier_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "supplier_memberships_tenant_id_supplier_id_fkey" FOREIGN KEY ("tenant_id", "supplier_id") REFERENCES "Supplier"("tenant_id", "id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "supplier_memberships_user_id_tenant_id_supplier_id_key" ON "supplier_memberships"("user_id", "tenant_id", "supplier_id");
CREATE INDEX "supplier_memberships_tenant_id_user_id_status_idx" ON "supplier_memberships"("tenant_id", "user_id", "status");
CREATE INDEX "supplier_memberships_tenant_id_supplier_id_idx" ON "supplier_memberships"("tenant_id", "supplier_id");

CREATE TABLE "supplier_room_drafts" (
  "id" TEXT NOT NULL,
  "tenant_id" TEXT NOT NULL,
  "supplier_id" TEXT NOT NULL,
  "hotel_id" TEXT NOT NULL,
  "room_type_id" TEXT NOT NULL,
  "supplier_notes" VARCHAR(500) NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "supplier_room_drafts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "supplier_room_drafts_notes_check" CHECK (char_length(btrim("supplier_notes")) BETWEEN 1 AND 500),
  CONSTRAINT "supplier_room_drafts_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "supplier_room_drafts_tenant_id_supplier_id_fkey" FOREIGN KEY ("tenant_id", "supplier_id") REFERENCES "Supplier"("tenant_id", "id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "supplier_room_drafts_tenant_id_hotel_id_fkey" FOREIGN KEY ("tenant_id", "hotel_id") REFERENCES "Hotel"("tenant_id", "id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "supplier_room_drafts_hotel_id_room_type_id_fkey" FOREIGN KEY ("hotel_id", "room_type_id") REFERENCES "RoomType"("hotel_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "supplier_room_drafts_tenant_id_supplier_id_room_type_id_key" ON "supplier_room_drafts"("tenant_id", "supplier_id", "room_type_id");
CREATE INDEX "supplier_room_drafts_tenant_id_supplier_id_hotel_id_idx" ON "supplier_room_drafts"("tenant_id", "supplier_id", "hotel_id");

ALTER TABLE "supplier_memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "supplier_memberships" FORCE ROW LEVEL SECURITY;
CREATE POLICY "supplier_memberships_tenant_isolation" ON "supplier_memberships"
  USING ("tenant_id" = "fbeds_current_tenant_id"())
  WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

ALTER TABLE "supplier_room_drafts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "supplier_room_drafts" FORCE ROW LEVEL SECURITY;
CREATE POLICY "supplier_room_drafts_tenant_supplier_isolation" ON "supplier_room_drafts"
  USING (
    "tenant_id" = "fbeds_current_tenant_id"()
    AND "supplier_id" = NULLIF(current_setting('app.current_supplier_id', true), '')
  )
  WITH CHECK (
    "tenant_id" = "fbeds_current_tenant_id"()
    AND "supplier_id" = NULLIF(current_setting('app.current_supplier_id', true), '')
  );

INSERT INTO "Permission" ("id", "key", "description") VALUES
  ('perm_supplier_extranet_hotels_read', 'supplier.extranet.hotels.read', 'Read hotels mapped to the authenticated supplier organization'),
  ('perm_supplier_extranet_rooms_read', 'supplier.extranet.rooms.read', 'Read rooms of hotels mapped to the authenticated supplier organization'),
  ('perm_supplier_extranet_drafts_manage', 'supplier.extranet.drafts.manage', 'Save a private room note for the authenticated supplier organization')
ON CONFLICT ("key") DO UPDATE SET "description" = EXCLUDED."description";

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT ON "supplier_memberships" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "supplier_room_drafts" TO fbeds_api';
  END IF;
END $$;
