export const businessTypes = ['Travel agency', 'Tour operator', 'DMC', 'Hotel or hotel group', 'Travel technology', 'Other'] as const
export const volumeOptions = ['Fewer than 100', '100–999', '1,000–9,999', '10,000 or more', 'Not yet known'] as const
export const interestAreas = ['Hotel supply', 'B2B distribution', 'Supplier extranet', 'Agent booking tools', 'API or XML connectivity', 'Other'] as const
export type LeadInput = { fullName: string; businessEmail: string; company: string; market: string; businessType: string; monthlyVolume: string; interestArea: string; message: string; consent: boolean; website: string }
export type LeadField = Exclude<keyof LeadInput, 'website'>
export type LeadErrors = Partial<Record<LeadField | 'form', string>>
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
export function leadFromFormData(formData: FormData): LeadInput { const text = (key: string) => String(formData.get(key) ?? '').trim(); return { fullName: text('fullName'), businessEmail: text('businessEmail'), company: text('company'), market: text('market'), businessType: text('businessType'), monthlyVolume: text('monthlyVolume'), interestArea: text('interestArea'), message: text('message'), consent: formData.get('consent') === 'on', website: text('website') } }
export function validateLead(input: LeadInput): LeadErrors { const errors: LeadErrors = {}; if (input.fullName.length < 2) errors.fullName = 'Enter your full name.'; if (!emailPattern.test(input.businessEmail)) errors.businessEmail = 'Enter a valid business email address.'; if (input.company.length < 2) errors.company = 'Enter your company name.'; if (input.market.length < 2) errors.market = 'Enter your country or primary market.'; if (!businessTypes.includes(input.businessType as typeof businessTypes[number])) errors.businessType = 'Select your business type.'; if (!volumeOptions.includes(input.monthlyVolume as typeof volumeOptions[number])) errors.monthlyVolume = 'Select an estimated monthly volume.'; if (!interestAreas.includes(input.interestArea as typeof interestAreas[number])) errors.interestArea = 'Select an area of interest.'; if (input.message.length < 20) errors.message = 'Tell us a little more in at least 20 characters.'; if (input.message.length > 2000) errors.message = 'Keep your message below 2,000 characters.'; if (!input.consent) errors.consent = 'Confirm that fBeds may respond to your enquiry.'; if (input.website) errors.form = 'This submission could not be accepted.'; return errors }
