import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, CheckCircle2 } from 'lucide-react'

const pages: Record<string, { eyebrow: string; title: string; intro: string; bullets: string[] }> = {
  about: { eyebrow: 'The company', title: 'The connected layer behind better hotel distribution.', intro: 'FBEDS is building the operating infrastructure that helps hospitality businesses connect inventory, demand and technology with less friction.', bullets: ['Built for the complexity of B2B travel', 'Designed around dependable connectivity', 'Focused on measurable commercial outcomes'] },
  technology: { eyebrow: 'Technology', title: 'Modern connectivity for a market that never stops moving.', intro: 'Our platform brings content, rates, availability and booking workflows together through clear, resilient infrastructure.', bullets: ['API-first architecture', 'Structured hotel content', 'Reliable booking workflows'] },
  inventory: { eyebrow: 'Inventory', title: 'One operating view for a world of hotel supply.', intro: 'Organise contracted and dynamic inventory so teams can move faster, make better decisions and distribute with confidence.', bullets: ['Contracted and dynamic supply', 'Rate and availability controls', 'Buyer-ready hotel content'] },
  api: { eyebrow: 'API & connectivity', title: 'Connect your product to hotel distribution.', intro: 'Give your travel technology a reliable foundation for search, availability, booking and content without reinventing the infrastructure.', bullets: ['Search and availability endpoints', 'Structured content and mapping', 'Clear integration pathways'] },
  supplier: { eyebrow: 'For suppliers', title: 'Turn your supply into a stronger distribution channel.', intro: 'FBEDS helps suppliers and DMCs connect inventory to qualified global buyers while keeping commercial control close.', bullets: ['Wider buyer access', 'Flexible distribution rules', 'Operational visibility'] },
  agent: { eyebrow: 'For travel sellers', title: 'Search and book with clarity.', intro: 'A faster way for agencies and tour operators to discover competitive hotel content and turn it into confident bookings.', bullets: ['Competitive B2B rates', 'Fast search and reliable availability', 'Booking tools built for daily use'] },
  pricing: { eyebrow: 'Pricing', title: 'A commercial model that scales with your distribution.', intro: 'Every distribution business is different. Talk to us about the markets, inventory and connectivity you need to bring together.', bullets: ['Tailored to your operating model', 'Transparent commercial conversation', 'Built for growth'] },
  resources: { eyebrow: 'Resources', title: 'Practical thinking for modern hotel distribution.', intro: 'Explore perspectives on connectivity, inventory operations and the commercial systems shaping B2B travel.', bullets: ['Distribution strategy', 'Hotel technology', 'Commercial operations'] },
  careers: { eyebrow: 'Careers', title: 'Help build the infrastructure for global hospitality.', intro: 'We are looking for thoughtful builders who care about useful technology, clear systems and the people who depend on them.', bullets: ['Product and engineering', 'Hospitality domain expertise', 'A culture of ownership'] },
  contact: { eyebrow: 'Contact', title: 'Let&apos;s talk about what you are building.', intro: 'Whether you are distributing rooms, sourcing inventory or connecting a travel product, the FBEDS team is ready to understand your goals.', bullets: ['Tell us about your business', 'Find the right FBEDS solution', 'Plan your next connection'] },
  'request-demo': { eyebrow: 'Request a demo', title: 'See how FBEDS fits your distribution model.', intro: 'Share a few details and our team will get in touch to walk through the platform and the opportunities in your market.', bullets: ['Platform walkthrough', 'Connectivity discussion', 'Commercial fit'] },
  login: { eyebrow: 'Portal access', title: 'Welcome back to FBEDS.', intro: 'Choose the portal that matches your role and continue to your workspace.', bullets: ['Agent portal', 'Supplier portal', 'Admin operations'] },
  privacy: { eyebrow: 'Legal', title: 'Privacy at FBEDS.', intro: 'We are committed to handling business and user information with care, clarity and appropriate security.', bullets: ['Responsible data handling', 'Clear communication', 'Security-first operations'] },
}

export default async function PublicPage({ params }: { params: Promise<{ slug: string[] }> }) {
  const { slug } = await params
  const key = slug.join('/')
  const page = pages[key] ?? pages.about
  return <main className="min-h-screen bg-white"><header className="border-b border-border"><div className="container-wide flex h-20 items-center justify-between"><Link href="/" className="flex items-center gap-3 font-extrabold tracking-[-.05em]"><span className="flex size-9 items-center justify-center rounded-[4px] bg-brand text-lg text-white">F</span>FBEDS<span className="text-brand">.</span></Link><Link href="/request-demo" className="inline-flex items-center gap-2 rounded-[4px] bg-brand px-4 py-2.5 text-sm font-bold text-white">Request a demo <ArrowUpRight size={15} /></Link></div></header><div className="container-wide py-16 lg:py-24"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#6b7280] hover:text-brand"><ArrowLeft size={16} /> Back home</Link><div className="mt-12 grid gap-12 lg:grid-cols-[1fr_.7fr]"><div><p className="eyebrow">{page.eyebrow}</p><h1 className="mt-4 max-w-3xl text-balance text-5xl font-extrabold leading-[1.03] tracking-[-.06em] sm:text-7xl" dangerouslySetInnerHTML={{ __html: page.title }} /><p className="mt-7 max-w-2xl text-pretty text-lg leading-8 text-[#6b7280]">{page.intro}</p><Link href="/request-demo" className="mt-9 inline-flex items-center gap-2 rounded-[4px] bg-brand px-5 py-3.5 text-sm font-bold text-white hover:bg-brand-dark">Start a conversation <ArrowUpRight size={16} /></Link></div><div className="h-fit border border-border bg-muted p-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#6b7280]">What to expect</p><div className="mt-6 flex flex-col gap-5">{page.bullets.map((bullet) => <div key={bullet} className="flex gap-3 text-sm font-semibold"><CheckCircle2 size={19} className="shrink-0 text-trust" />{bullet}</div>)}</div></div></div></div></main>
}
