import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import { PrismaService } from '../database/prisma.service'
import { AgentAuditService } from '../agent/audit.service'
import type { Prisma } from '@prisma/client'

const date = (value: string) => { const parsed = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(parsed.getTime())) throw new BadRequestException('Invalid date'); return parsed }
const clean = (value: unknown): string => typeof value === 'string' ? value.trim() : ''

@Injectable()
export class SupplyService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AgentAuditService) { void this.audit }
  private async permitted(tenantId: string, userId: string, permission: string) {
    const result: any[] = await this.prisma.withTenant(tenantId, tx => tx.userRole.findMany({ where: { tenantId, userId, role: { tenantId } }, include: { role: { include: { permissions: { include: { permission: true } } } } } })) as any[]
    const keys = result.flatMap((role: any) => role.role.permissions.map((item: any) => item.permission.key))
    if (!keys.includes(permission)) throw new ForbiddenException('Insufficient permission')
  }
  private async check(tenantId: string, userId: string, permission: string) { await this.permitted(tenantId, userId, permission) }
  private async write<T>(tenantId: string, userId: string, permission: string, action: string, entityType: string, requestId: string | undefined, work: (tx: Prisma.TransactionClient) => Promise<{ id: string; value: T }>) {
    await this.check(tenantId, userId, permission)
    return this.prisma.withTenant(tenantId, async tx => {
      const result = await work(tx)
      await tx.auditEvent.create({ data: { tenantId, userId, actorType: 'USER', action, entityType, entityId: result.id, payload: { outcome: 'allowed', requestId: requestId ?? null } } })
      return result.value
    })
  }
  async hotels(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.hotels.read'); return this.prisma.withTenant(tenantId, tx => tx.hotel.findMany({ where: { tenantId }, orderBy: { name: 'asc' } })) }
  async hotel(tenantId: string, userId: string, hotelId: string) { await this.check(tenantId, userId, 'supply.hotels.read'); const hotel = await this.prisma.withTenant(tenantId, tx => tx.hotel.findFirst({ where: { id: hotelId, tenantId }, include: { roomTypes: { where: { isActive: true }, orderBy: { name: 'asc' } } } })); if (!hotel) throw new NotFoundException('Hotel not found'); return hotel }
  private hotelData(tenantId: string, input: any) { const name = clean(input.name); const propertyType = clean(input.propertyType); const city = clean(input.city); const countryCode = clean(input.countryCode).toUpperCase(); const timeZone = clean(input.timeZone) || 'Asia/Dubai'; if (!name || !propertyType || !city || !/^[A-Z]{2}$/.test(countryCode) || (input.starRating !== undefined && input.starRating !== null && (!Number.isInteger(input.starRating) || input.starRating < 1 || input.starRating > 5))) throw new BadRequestException('Invalid hotel fields'); return { tenantId, name, propertyType, starRating: input.starRating ?? null, address: input.address == null ? null : clean(input.address), city, countryCode, timeZone, externalRef: input.externalRef == null ? null : clean(input.externalRef) } }
  async createHotel(tenantId: string, userId: string, input: any, requestId?: string) { const data = this.hotelData(tenantId, input); return this.write(tenantId, userId, 'supply.hotels.manage', 'supply.hotel.created', 'hotel', requestId, async tx => { const value = await tx.hotel.create({ data }); return { id: value.id, value } }) }
  async updateHotel(tenantId: string, userId: string, hotelId: string, input: any, requestId?: string) { const allowed = ['name', 'propertyType', 'starRating', 'address', 'city', 'countryCode', 'timeZone', 'externalRef']; if (Object.keys(input).some((key) => !allowed.includes(key) || key === 'tenantId')) throw new BadRequestException('Invalid hotel fields'); const current = await this.prisma.withTenant(tenantId, tx => tx.hotel.findFirst({ where: { id: hotelId, tenantId } })); if (!current) throw new NotFoundException('Hotel not found'); const data = this.hotelData(tenantId, { ...current, ...input }); return this.write(tenantId, userId, 'supply.hotels.manage', 'supply.hotel.updated', 'hotel', requestId, async tx => { const value = await tx.hotel.update({ where: { id: hotelId }, data }); return { id: value.id, value } }) }
  async roomTypes(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rooms.read'); return this.prisma.withTenant(tenantId, tx => tx.roomType.findMany({ where: { hotel: { tenantId } }, orderBy: { name: 'asc' } })) }
  async createRoomType(tenantId: string, userId: string, input: any, requestId?: string) { if (!Number.isInteger(input.maxAdults) || !Number.isInteger(input.maxChildren ?? 0) || !Number.isInteger(input.maxOccupancy) || input.maxAdults < 1 || (input.maxChildren ?? 0) < 0 || input.maxOccupancy < input.maxAdults + (input.maxChildren ?? 0)) throw new BadRequestException('Invalid occupancy'); return this.write(tenantId, userId, 'supply.rooms.manage', 'supply.room.created', 'room_type', requestId, async tx => { const hotel = await tx.hotel.findFirst({ where: { id: input.hotelId, tenantId } }); if (!hotel) throw new BadRequestException('Hotel does not belong to tenant'); const value = await tx.roomType.create({ data: { hotelId: input.hotelId, name: clean(input.name), code: clean(input.code), maxAdults: input.maxAdults, maxChildren: input.maxChildren ?? 0, maxOccupancy: input.maxOccupancy, beddingMetadata: input.beddingMetadata ?? {} } }); return { id: value.id, value } }) }
  async boardBases(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rates.read'); return this.prisma.withTenant(tenantId, tx => tx.boardBasis.findMany({ where: { tenantId, isActive: true }, orderBy: { code: 'asc' } })) }
  async contracts(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.contracts.read'); return this.prisma.withTenant(tenantId, tx => tx.contract.findMany({ where: { tenantId }, orderBy: { validFrom: 'desc' } })) }
  async createContract(tenantId: string, userId: string, input: any, requestId?: string) { const from = date(input.validFrom); const to = date(input.validTo); if (to < from) throw new BadRequestException('Invalid contract validity'); return this.write(tenantId, userId, 'supply.contracts.manage', 'supply.contract.created', 'contract', requestId, async tx => { const supplier = await tx.supplier.findFirst({ where: { id: input.supplierId, tenantId } }); if (!supplier) throw new BadRequestException('Supplier does not belong to tenant'); if (input.supplierHotelMappingId) { const mapping = await tx.supplierHotelMapping.findFirst({ where: { id: input.supplierHotelMappingId, tenantId, supplierId: input.supplierId, status: 'MAPPED' } }); if (!mapping) throw new BadRequestException('Invalid supplier hotel mapping') } const value = await tx.contract.create({ data: { tenantId, supplierId: input.supplierId, supplierHotelMappingId: input.supplierHotelMappingId ?? null, code: clean(input.code), validFrom: from, validTo: to, settlementCurrency: clean(input.settlementCurrency).toUpperCase(), salesMarkets: input.salesMarkets ?? [], nationalities: input.nationalities ?? [] } }); return { id: value.id, value } }) }
  async ratePlans(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rates.read'); return this.prisma.withTenant(tenantId, tx => tx.ratePlan.findMany({ where: { tenantId }, include: { contract: true, roomType: true, boardBasis: true }, orderBy: { code: 'asc' } })) }
  async createRatePlan(tenantId: string, userId: string, input: any, requestId?: string) { if (!Number.isInteger(input.occupancy) || input.occupancy < 1) throw new BadRequestException('Invalid occupancy'); return this.write(tenantId, userId, 'supply.rates.manage', 'supply.rate_plan.created', 'rate_plan', requestId, async tx => { const contract = await tx.contract.findFirst({ where: { id: input.contractId, tenantId }, include: { supplierHotelMapping: true } }); const room = await tx.roomType.findFirst({ where: { id: input.roomTypeId, hotel: { tenantId } } }); const board = await tx.boardBasis.findFirst({ where: { id: input.boardBasisId, tenantId, isActive: true } }); if (!contract || !room || !board) throw new BadRequestException('Invalid rate plan relationship'); if (contract.supplierHotelMapping && contract.supplierHotelMapping.hotelId !== room.hotelId) throw new BadRequestException('Contract and room hotel mismatch'); const value = await tx.ratePlan.create({ data: { tenantId, contractId: input.contractId, roomTypeId: input.roomTypeId, boardBasisId: input.boardBasisId, code: clean(input.code), occupancy: input.occupancy, currency: clean(input.currency).toUpperCase(), refundable: input.refundable ?? true, taxesIncluded: input.taxesIncluded ?? false, feesIncluded: input.feesIncluded ?? false, minStay: input.minStay ?? 1, maxStay: input.maxStay ?? null, releaseDays: input.releaseDays ?? 0 } }); return { id: value.id, value } }) }
  async upsertDailyRate(tenantId: string, userId: string, input: any, requestId?: string) { if ((!Number.isSafeInteger(input.amountMinor) && typeof input.amountMinor !== 'string') || !Number.isInteger(input.occupancy)) throw new BadRequestException('Invalid daily rate'); const amountMinor = BigInt(input.amountMinor); if (amountMinor < 0n) throw new BadRequestException('amountMinor must be non-negative'); return this.write(tenantId, userId, 'supply.rates.manage', 'supply.daily_rate.updated', 'daily_rate', requestId, async tx => { const plan = await tx.ratePlan.findFirst({ where: { id: input.ratePlanId, tenantId } }); if (!plan || plan.currency !== clean(input.currency).toUpperCase()) throw new BadRequestException('Rate plan or currency is invalid'); const value = await tx.dailyRate.upsert({ where: { ratePlanId_stayDate_occupancy: { ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), occupancy: input.occupancy } }, update: { amountMinor, currency: clean(input.currency).toUpperCase() }, create: { tenantId, ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), occupancy: input.occupancy, amountMinor, currency: clean(input.currency).toUpperCase() } }); return { id: value.id, value: { ...value, amountMinor: value.amountMinor.toString() } } }) }
  async upsertAvailability(tenantId: string, userId: string, input: any, requestId?: string) { if (!Number.isInteger(input.allotment) || !Number.isInteger(input.sold) || input.allotment < 0 || input.sold < 0 || input.sold > input.allotment) throw new BadRequestException('Invalid availability'); return this.write(tenantId, userId, 'supply.availability.manage', 'supply.availability.updated', 'daily_availability', requestId, async tx => { const plan = await tx.ratePlan.findFirst({ where: { id: input.ratePlanId, tenantId } }); if (!plan) throw new BadRequestException('Rate plan does not belong to tenant'); const value = await tx.dailyAvailability.upsert({ where: { ratePlanId_stayDate: { ratePlanId: input.ratePlanId, stayDate: date(input.stayDate) } }, update: { allotment: input.allotment, sold: input.sold, stopSell: input.stopSell ?? false, minStay: input.minStay ?? 1 }, create: { tenantId, ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), allotment: input.allotment, sold: input.sold, stopSell: input.stopSell ?? false, minStay: input.minStay ?? 1 } }); return { id: value.id, value } }) }
  async sellability(tenantId: string, userId: string, input: any) { await this.check(tenantId, userId, 'supply.rates.read'); const stayDate = date(input.stayDate); const plan = await this.prisma.withTenant(tenantId, tx => tx.ratePlan.findFirst({ where: { id: input.ratePlanId, tenantId }, include: { roomType: { include: { hotel: true } }, boardBasis: true, contract: { include: { supplier: true, supplierHotelMapping: true } }, dailyRates: { where: { stayDate, occupancy: input.occupancy } }, availability: { where: { stayDate } } } })); const reasons: string[] = []; if (!plan) reasons.push('RATE_PLAN_MISSING'); else { if (plan.roomType.hotel.contentStatus === 'SUSPENDED') reasons.push('HOTEL_INACTIVE'); if (!plan.roomType.isActive) reasons.push('ROOM_TYPE_INACTIVE'); if (!plan.boardBasis.isActive) reasons.push('BOARD_BASIS_INACTIVE'); if (plan.contract.status !== 'ACTIVE') reasons.push('CONTRACT_INACTIVE'); if (stayDate < plan.contract.validFrom || stayDate > plan.contract.validTo) reasons.push('OUTSIDE_CONTRACT_VALIDITY'); if (plan.contract.supplierHotelMapping && (plan.contract.supplierHotelMapping.hotelId !== plan.roomType.hotelId || plan.contract.supplierHotelMapping.status !== 'MAPPED')) reasons.push('SUPPLIER_MAPPING_INVALID'); if (plan.status !== 'ACTIVE') reasons.push('RATE_PLAN_INACTIVE'); if (!plan.dailyRates[0] || plan.dailyRates[0].amountMinor < 0n) reasons.push('DAILY_RATE_MISSING_OR_INVALID'); const availability = plan.availability[0]; if (!availability) reasons.push('AVAILABILITY_MISSING'); else { if (availability.stopSell) reasons.push('STOP_SELL'); if (availability.allotment - availability.sold <= 0) reasons.push('NO_INVENTORY') } } return { eligible: reasons.length === 0, status: reasons.length === 0 ? 'ELIGIBLE_FOR_FUTURE_SEARCH' : 'NOT_ELIGIBLE', reasons } } }
