import { BadRequestException, ForbiddenException, Injectable } from '@nestjs/common'
import { PrismaService } from '../database/prisma.service'
import { AgentAuditService } from '../agent/audit.service'
import type { Prisma } from '@prisma/client'

const date = (value: string) => { const parsed = new Date(`${value}T00:00:00.000Z`); if (Number.isNaN(parsed.getTime())) throw new BadRequestException('Invalid date'); return parsed }
const clean = (value: unknown): string => typeof value === 'string' ? value.trim() : ''

@Injectable()
export class SupplyService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AgentAuditService) { void this.audit }
  private async permitted(tenantId: string, userId: string, permission: string) {
    const result: any[] = await this.prisma.withTenant(tenantId, tx => tx.userRole.findMany({ where: { tenantId, userId, role: { tenantId } }, include: { role: { include: { permissions: { include: { permission: true } } } } } })) as any[]
    const keys = result.flatMap((role: any) => role.role.permissions.map((item: any) => item.permission.key))
    if (!keys.includes(permission)) throw new ForbiddenException('Insufficient permission')
  }
  private async check(tenantId: string, userId: string, permission: string) { await this.permitted(tenantId, userId, permission) }
  private async write<T>(tenantId: string, userId: string, permission: string, action: string, entityType: string, entityId: string, work: (tx: Prisma.TransactionClient) => Promise<T>) {
    await this.check(tenantId, userId, permission)
    return this.prisma.withTenant(tenantId, async tx => { const value = await work(tx); await tx.auditEvent.create({ data: { tenantId, userId, actorType: 'USER', action, entityType, entityId, payload: { requestId: undefined } } }); return value })
  }
  async hotels(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.hotels.read'); return this.prisma.withTenant(tenantId, tx => tx.hotel.findMany({ where: { tenantId }, orderBy: { name: 'asc' } })) }
  async createHotel(tenantId: string, userId: string, input: any) { return this.write(tenantId, userId, 'supply.hotels.manage', 'supply.hotel.created', 'hotel', 'new', tx => tx.hotel.create({ data: { tenantId, name: clean(input.name), propertyType: clean(input.propertyType), starRating: input.starRating ?? null, address: input.address ?? null, city: clean(input.city), countryCode: clean(input.countryCode).toUpperCase(), timeZone: input.timeZone ?? 'Asia/Dubai', externalRef: input.externalRef ?? null } })) }
  async roomTypes(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rooms.read'); return this.prisma.withTenant(tenantId, tx => tx.roomType.findMany({ where: { hotel: { tenantId } }, orderBy: { name: 'asc' } })) }
  async createRoomType(tenantId: string, userId: string, input: any) { if (input.maxAdults < 1 || input.maxChildren < 0 || input.maxOccupancy < input.maxAdults + input.maxChildren) throw new BadRequestException('Invalid occupancy'); return this.write(tenantId, userId, 'supply.rooms.manage', 'supply.room.created', 'room_type', 'new', tx => tx.roomType.create({ data: { hotelId: input.hotelId, name: clean(input.name), code: clean(input.code), maxAdults: input.maxAdults, maxChildren: input.maxChildren ?? 0, maxOccupancy: input.maxOccupancy, beddingMetadata: input.beddingMetadata ?? {} } })) }
  async boardBases(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rates.read'); return this.prisma.withTenant(tenantId, tx => tx.boardBasis.findMany({ where: { tenantId, isActive: true }, orderBy: { code: 'asc' } })) }
  async contracts(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.contracts.read'); return this.prisma.withTenant(tenantId, tx => tx.contract.findMany({ where: { tenantId }, orderBy: { validFrom: 'desc' } })) }
  async createContract(tenantId: string, userId: string, input: any) { const from = date(input.validFrom); const to = date(input.validTo); if (to < from) throw new BadRequestException('Invalid contract validity'); return this.write(tenantId, userId, 'supply.contracts.manage', 'supply.contract.created', 'contract', 'new', tx => tx.contract.create({ data: { tenantId, supplierId: input.supplierId, supplierHotelMappingId: input.supplierHotelMappingId ?? null, code: clean(input.code), validFrom: from, validTo: to, settlementCurrency: clean(input.settlementCurrency).toUpperCase(), salesMarkets: input.salesMarkets ?? [], nationalities: input.nationalities ?? [] } })) }
  async ratePlans(tenantId: string, userId: string) { await this.check(tenantId, userId, 'supply.rates.read'); return this.prisma.withTenant(tenantId, tx => tx.ratePlan.findMany({ where: { tenantId }, include: { contract: true, roomType: true, boardBasis: true }, orderBy: { code: 'asc' } })) }
  async createRatePlan(tenantId: string, userId: string, input: any) { if (input.occupancy < 1) throw new BadRequestException('Invalid occupancy'); return this.write(tenantId, userId, 'supply.rates.manage', 'supply.rate_plan.created', 'rate_plan', 'new', tx => tx.ratePlan.create({ data: { tenantId, contractId: input.contractId, roomTypeId: input.roomTypeId, boardBasisId: input.boardBasisId, code: clean(input.code), occupancy: input.occupancy, currency: clean(input.currency).toUpperCase(), refundable: input.refundable ?? true, taxesIncluded: input.taxesIncluded ?? false, feesIncluded: input.feesIncluded ?? false, minStay: input.minStay ?? 1, maxStay: input.maxStay ?? null, releaseDays: input.releaseDays ?? 0 } })) }
  async upsertDailyRate(tenantId: string, userId: string, input: any) { if (!Number.isSafeInteger(input.amountMinor) && typeof input.amountMinor !== 'string') throw new BadRequestException('amountMinor must be an integer'); const amountMinor = BigInt(input.amountMinor); if (amountMinor < 0n) throw new BadRequestException('amountMinor must be non-negative'); return this.write(tenantId, userId, 'supply.rates.manage', 'supply.daily_rate.updated', 'daily_rate', `${input.ratePlanId}:${input.stayDate}:${input.occupancy}`, tx => tx.dailyRate.upsert({ where: { ratePlanId_stayDate_occupancy: { ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), occupancy: input.occupancy } }, update: { amountMinor, currency: clean(input.currency).toUpperCase() }, create: { tenantId, ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), occupancy: input.occupancy, amountMinor, currency: clean(input.currency).toUpperCase() } })) }
  async upsertAvailability(tenantId: string, userId: string, input: any) { if (input.allotment < 0 || input.sold < 0 || input.sold > input.allotment) throw new BadRequestException('Invalid availability'); return this.write(tenantId, userId, 'supply.availability.manage', 'supply.availability.updated', 'daily_availability', `${input.ratePlanId}:${input.stayDate}`, tx => tx.dailyAvailability.upsert({ where: { ratePlanId_stayDate: { ratePlanId: input.ratePlanId, stayDate: date(input.stayDate) } }, update: { allotment: input.allotment, sold: input.sold, stopSell: input.stopSell ?? false, minStay: input.minStay ?? 1 }, create: { tenantId, ratePlanId: input.ratePlanId, stayDate: date(input.stayDate), allotment: input.allotment, sold: input.sold, stopSell: input.stopSell ?? false, minStay: input.minStay ?? 1 } })) }
  async sellability(tenantId: string, userId: string, input: any) { await this.check(tenantId, userId, 'supply.rates.read'); const stayDate = date(input.stayDate); const plan = await this.prisma.withTenant(tenantId, tx => tx.ratePlan.findFirst({ where: { id: input.ratePlanId, tenantId }, include: { roomType: { include: { hotel: true } }, boardBasis: true, contract: { include: { supplier: true, supplierHotelMapping: true } }, dailyRates: { where: { stayDate, occupancy: input.occupancy } }, availability: { where: { stayDate } } } })); const reasons: string[] = []; if (!plan) reasons.push('RATE_PLAN_MISSING'); else { if (plan.roomType.hotel.contentStatus === 'SUSPENDED') reasons.push('HOTEL_INACTIVE'); if (!plan.roomType.isActive) reasons.push('ROOM_TYPE_INACTIVE'); if (!plan.boardBasis.isActive) reasons.push('BOARD_BASIS_INACTIVE'); if (plan.contract.status !== 'ACTIVE') reasons.push('CONTRACT_INACTIVE'); if (stayDate < plan.contract.validFrom || stayDate > plan.contract.validTo) reasons.push('OUTSIDE_CONTRACT_VALIDITY'); if (plan.contract.supplierHotelMapping && (plan.contract.supplierHotelMapping.hotelId !== plan.roomType.hotelId || plan.contract.supplierHotelMapping.status !== 'MAPPED')) reasons.push('SUPPLIER_MAPPING_INVALID'); if (plan.status !== 'ACTIVE') reasons.push('RATE_PLAN_INACTIVE'); if (!plan.dailyRates[0] || plan.dailyRates[0].amountMinor < 0n) reasons.push('DAILY_RATE_MISSING_OR_INVALID'); const availability = plan.availability[0]; if (!availability) reasons.push('AVAILABILITY_MISSING'); else { if (availability.stopSell) reasons.push('STOP_SELL'); if (availability.allotment - availability.sold <= 0) reasons.push('NO_INVENTORY') } } return { eligible: reasons.length === 0, status: reasons.length === 0 ? 'ELIGIBLE_FOR_FUTURE_SEARCH' : 'NOT_ELIGIBLE', reasons } } }
