import type { LucideIcon } from 'lucide-react'
import { BadgeDollarSign, BadgePercent, BarChart3, BedDouble, BookOpenCheck, Boxes, CalendarDays, CircleHelp, FileCheck2, Link2, ReceiptText, Settings, Tags, TicketCheck, TriangleAlert, UsersRound } from 'lucide-react'
import type { StatusTone } from './types'

export interface ModuleStat { label: string; value: string; detail: string }
export interface ModuleRow { id: string; cells: string[]; status: string; tone?: StatusTone }
export interface ModuleConfig { eyebrow: string; title: string; description: string; action: string; icon: LucideIcon; stats: ModuleStat[]; columns: string[]; rows: ModuleRow[]; notice?: { title: string; detail: string; tone: StatusTone } }

export const moduleConfigs = {
  rooms: { eyebrow: 'Hotel content', title: 'Rooms', description: 'Maintain room types, occupancy, amenities, meal plans and content readiness across your hotel portfolio.', action: 'Add room type', icon: BedDouble,
    stats: [{ label: 'Room types', value: '74', detail: 'Across 12 properties' }, { label: 'Content complete', value: '89%', detail: 'Portfolio average' }, { label: 'Missing photos', value: '8', detail: 'Across 3 room types' }, { label: 'Policy review', value: '4', detail: 'Items need attention' }], columns: ['Room type', 'Property', 'Occupancy', 'Meal plans', 'Content score'], rows: [
      { id: 'RM-1048', cells: ['Deluxe King', 'Meridian Grand Dubai', '2 adults + 1 child', 'RO · BB · HB', '96%'], status: 'Ready', tone: 'success' }, { id: 'RM-1081', cells: ['Executive Sea View', 'Meridian Corniche', '3 adults', 'BB · HB', '82%'], status: 'Review', tone: 'warning' }, { id: 'RM-1173', cells: ['Superior Twin', 'Harbour View Muscat', '2 adults', 'RO · BB', '71%'], status: 'Missing content', tone: 'danger' }] },
  contracts: { eyebrow: 'Commercial setup', title: 'Contracts', description: 'Review commercial terms, validity periods, cancellation rules, supplements and release conditions.', action: 'Create contract draft', icon: BookOpenCheck,
    stats: [{ label: 'Active contracts', value: '18', detail: '12 properties' }, { label: 'Rate plans', value: '42', detail: '31 active' }, { label: 'Expiring soon', value: '3', detail: 'Within 30 days' }, { label: 'Draft changes', value: '6', detail: 'Not published' }], columns: ['Contract', 'Property', 'Validity', 'Commercial model', 'Rate plans'], rows: [
      { id: 'CTR-2026-041', cells: ['Winter 2026 FIT', 'Meridian Grand Dubai', '01 Oct 2026 – 31 Mar 2027', 'Fixed net · AED', '6 plans'], status: 'Active', tone: 'success' }, { id: 'CTR-2026-038', cells: ['Autumn GCC', 'Meridian Corniche', '01 Sep – 30 Nov 2026', 'Fixed net · AED', '4 plans'], status: 'Expiring soon', tone: 'warning' }, { id: 'CTR-2026-052', cells: ['Oman Winter Series', 'Harbour View Muscat', '15 Oct 2026 – 15 Apr 2027', 'Fixed net · OMR', '3 plans'], status: 'Draft', tone: 'neutral' }], notice: { title: 'UI calculation preview only', detail: 'Integer minor-unit examples are used. No supplier rate is being published or distributed from this interface.', tone: 'info' } },
  inventory: { eyebrow: 'Supply control', title: 'Availability & Inventory', description: 'Inspect allocations, stop-sells, release periods and stay restrictions across dates and room types.', action: 'Bulk update', icon: CalendarDays,
    stats: [{ label: 'Coverage', value: '93.4%', detail: 'Next 90 days' }, { label: 'Open allocation', value: '4,286', detail: 'Room nights' }, { label: 'Stop-sell dates', value: '12', detail: 'Across 4 properties' }, { label: 'Coverage gaps', value: '7', detail: 'Need review' }], columns: ['Property / room', 'Date range', 'Allocation', 'Release', 'Restrictions'], rows: [
      { id: 'INV-184', cells: ['Meridian Grand · Deluxe King', '17–30 Sep 2026', '12 / night', '3 days', 'Min stay 2'], status: 'Open', tone: 'success' }, { id: 'INV-211', cells: ['Meridian Corniche · Executive', '03–09 Oct 2026', '0 / night', '2 days', 'Stop sell'], status: 'Gap', tone: 'danger' }, { id: 'INV-248', cells: ['Harbour View · Superior Twin', '17 Sep–16 Oct 2026', '6 / night', '5 days', 'CTA 24 Sep'], status: 'Restricted', tone: 'warning' }], notice: { title: 'No live inventory publication', detail: 'Updates are visual drafts and are not sent to search, agents, channel managers or third parties.', tone: 'warning' } },
  rates: { eyebrow: 'Commercial setup', title: 'Rates', description: 'Maintain typed net-rate previews by hotel, room, meal plan and validity period.', action: 'Add rate draft', icon: Tags,
    stats: [{ label: 'Active rate plans', value: '31', detail: 'Across 12 hotels' }, { label: 'Draft changes', value: '6', detail: 'Not published' }, { label: 'Currencies', value: '2', detail: 'AED and OMR' }, { label: 'Review due', value: '4', detail: 'Before 30 Sep' }], columns: ['Rate plan', 'Hotel / room', 'Validity', 'Net rate', 'Meal plan'], rows: [
      { id: 'RTE-4102', cells: ['Flexible FIT', 'Meridian Grand · Deluxe King', '01 Oct 2026 – 31 Mar 2027', 'AED 625.00', 'Breakfast'], status: 'Active', tone: 'success' }, { id: 'RTE-4108', cells: ['Early Booker', 'Meridian Corniche · Executive', '01 Oct – 20 Dec 2026', 'AED 590.00', 'Half board'], status: 'Review', tone: 'warning' }, { id: 'RTE-4214', cells: ['Winter Wholesale', 'Harbour View · Superior Twin', '15 Oct 2026 – 15 Apr 2027', 'OMR 148.00', 'Room only'], status: 'Draft', tone: 'neutral' }], notice: { title: 'Rate preview only', detail: 'Amounts are UI mock values; no rate is published to search or distribution.', tone: 'info' } },
  availability: { eyebrow: 'Inventory control', title: 'Availability', description: 'Review daily room availability and coverage gaps across hotel room types.', action: 'Update availability', icon: CalendarDays,
    stats: [{ label: 'Coverage', value: '93.4%', detail: 'Next 90 days' }, { label: 'Available nights', value: '4,286', detail: 'Across all rooms' }, { label: 'Closed dates', value: '12', detail: 'Across 4 hotels' }, { label: 'Coverage gaps', value: '7', detail: 'Need review' }], columns: ['Hotel / room', 'Date range', 'Available', 'Sold', 'Coverage'], rows: [
      { id: 'AVL-184', cells: ['Meridian Grand · Deluxe King', '17–30 Sep 2026', '12 / night', '4 / night', '100%'], status: 'Open', tone: 'success' }, { id: 'AVL-211', cells: ['Meridian Corniche · Executive', '03–09 Oct 2026', '0 / night', '—', '0%'], status: 'Gap', tone: 'danger' }, { id: 'AVL-248', cells: ['Harbour View · Superior Twin', '17 Sep–16 Oct 2026', '6 / night', '2 / night', '94%'], status: 'Open', tone: 'success' }], notice: { title: 'No live inventory publication', detail: 'Updates remain visual drafts and are not sent to agents or third parties.', tone: 'warning' } },
  allotments: { eyebrow: 'Inventory control', title: 'Allotments', description: 'Track contracted room allocations, release periods and remaining allotment by hotel.', action: 'Add allotment draft', icon: FileCheck2,
    stats: [{ label: 'Active allotments', value: '28', detail: 'Across 11 hotels' }, { label: 'Room nights', value: '4,286', detail: 'Contracted balance' }, { label: 'Release due', value: '5', detail: 'Within 7 days' }, { label: 'Exhausted', value: '2', detail: 'Need review' }], columns: ['Allotment', 'Hotel / room', 'Validity', 'Allocation', 'Release'], rows: [
      { id: 'ALT-2201', cells: ['Winter FIT allocation', 'Meridian Grand · Deluxe King', '01 Oct 2026 – 31 Mar 2027', '12 / night', '3 days'], status: 'Active', tone: 'success' }, { id: 'ALT-2208', cells: ['GCC series allocation', 'Meridian Corniche · Executive', '01 Oct – 30 Nov 2026', '8 / night', '2 days'], status: 'Low balance', tone: 'warning' }, { id: 'ALT-2314', cells: ['Oman winter allocation', 'Harbour View · Superior Twin', '15 Oct 2026 – 15 Apr 2027', '6 / night', '5 days'], status: 'Draft', tone: 'neutral' }] },
  promotions: { eyebrow: 'Commercial setup', title: 'Promotions', description: 'Prepare early-booker, long-stay and tactical promotional rules for review.', action: 'Create promotion', icon: BadgePercent,
    stats: [{ label: 'Active promotions', value: '9', detail: 'Across 7 hotels' }, { label: 'Scheduled', value: '4', detail: 'Future start date' }, { label: 'Ending soon', value: '2', detail: 'Within 14 days' }, { label: 'Drafts', value: '3', detail: 'Not published' }], columns: ['Promotion', 'Hotels', 'Booking window', 'Stay window', 'Benefit'], rows: [
      { id: 'PRO-602', cells: ['Winter Early Booker', '4 hotels', 'Until 30 Sep 2026', '01 Nov 2026 – 31 Mar 2027', '15% preview'], status: 'Active', tone: 'success' }, { id: 'PRO-611', cells: ['Stay 4 Pay 3', 'Meridian Grand', '01–31 Oct 2026', '01 Nov – 20 Dec 2026', '1 night preview'], status: 'Scheduled', tone: 'info' }, { id: 'PRO-618', cells: ['GCC Weekend', '2 hotels', 'Open', 'Weekends only', '10% preview'], status: 'Draft', tone: 'neutral' }], notice: { title: 'Promotion preview only', detail: 'Benefits are not applied to sell prices until pricing contracts and approval workflows are connected.', tone: 'info' } },
  restrictions: { eyebrow: 'Inventory control', title: 'Restrictions', description: 'Review stop-sells, closed-to-arrival/departure rules and minimum-stay controls.', action: 'Add restriction', icon: TriangleAlert,
    stats: [{ label: 'Active restrictions', value: '18', detail: 'Across 6 hotels' }, { label: 'Stop-sells', value: '12', detail: 'Current and future' }, { label: 'Min-stay rules', value: '4', detail: 'Date-specific' }, { label: 'Ending today', value: '2', detail: 'Review required' }], columns: ['Restriction', 'Hotel / room', 'Date range', 'Rule', 'Reason'], rows: [
      { id: 'RST-731', cells: ['Expo blackout', 'Meridian Grand · All rooms', '10–14 Oct 2026', 'Stop sell', 'City event'], status: 'Scheduled', tone: 'warning' }, { id: 'RST-742', cells: ['Weekend arrival rule', 'Meridian Corniche · Executive', 'Every Friday', 'CTA', 'Yield control'], status: 'Active', tone: 'success' }, { id: 'RST-755', cells: ['Peak minimum stay', 'Harbour View · Superior Twin', '20 Dec 2026 – 05 Jan 2027', 'Min stay 3', 'Festive period'], status: 'Draft', tone: 'neutral' }] },
  bookings: { eyebrow: 'Reservations', title: 'Bookings', description: 'Review reservation status, stay details, supplier payable amounts and operational actions without exposing guest PII.', action: 'Export view', icon: Boxes,
    stats: [{ label: 'Arrivals today', value: '16', detail: '22 room nights' }, { label: 'In house', value: '31', detail: '42 rooms' }, { label: 'Action required', value: '2', detail: 'Within 2 hours' }, { label: 'This month', value: '186', detail: 'Confirmed bookings' }], columns: ['Booking', 'Property', 'Stay', 'Room / board', 'Payable'], rows: [
      { id: 'FBS-260916-1842', cells: ['FBS-260916-1842', 'Meridian Grand Dubai', '20–24 Sep 2026', 'Deluxe King · BB', 'AED 2,845.00'], status: 'Confirmed', tone: 'success' }, { id: 'FBS-260916-1798', cells: ['FBS-260916-1798', 'Meridian Corniche', '18–21 Sep 2026', 'Executive Sea View · HB', 'AED 1,960.00'], status: 'Action required', tone: 'danger' }, { id: 'FBS-260915-1664', cells: ['FBS-260915-1664', 'Harbour View Muscat', '23–26 Sep 2026', 'Superior Twin · RO', 'OMR 1,486.00'], status: 'Confirmed', tone: 'success' }] },
  vouchers: { eyebrow: 'Reservations', title: 'Vouchers', description: 'Preview supplier-facing accommodation vouchers with guest identity masked.', action: 'Export voucher list', icon: TicketCheck,
    stats: [{ label: 'Issued today', value: '14', detail: 'Confirmed stays' }, { label: 'Pending issue', value: '2', detail: 'Action required' }, { label: 'Reissued', value: '1', detail: 'This week' }, { label: 'This month', value: '172', detail: 'Voucher previews' }], columns: ['Voucher', 'Booking', 'Hotel', 'Stay', 'Version'], rows: [
      { id: 'VCH-260916-1842', cells: ['VCH-260916-1842', 'FBS-260916-1842', 'Meridian Grand Dubai', '20–24 Sep 2026', 'v1'], status: 'Issued', tone: 'success' }, { id: 'VCH-260916-1798', cells: ['VCH-260916-1798', 'FBS-260916-1798', 'Meridian Corniche', '18–21 Sep 2026', '—'], status: 'Pending', tone: 'warning' }, { id: 'VCH-260915-1664', cells: ['VCH-260915-1664', 'FBS-260915-1664', 'Harbour View Muscat', '23–26 Sep 2026', 'v2'], status: 'Reissued', tone: 'info' }], notice: { title: 'Documents are UI previews', detail: 'No live voucher is generated, stored or emailed from this interface.', tone: 'info' } },
  invoices: { eyebrow: 'Settlement workspace', title: 'Invoices', description: 'Track supplier invoice drafts, statement matching and settlement readiness using masked data.', action: 'Upload invoice', icon: ReceiptText,
    stats: [{ label: 'Pending review', value: '3', detail: 'AED 84,520' }, { label: 'Approved', value: '8', detail: 'Current cycle' }, { label: 'Disputed', value: '1', detail: 'Under review' }, { label: 'Next settlement', value: '24 Sep', detail: 'UI schedule preview' }], columns: ['Invoice', 'Statement period', 'Bookings', 'Supplier payable', 'Settlement'], rows: [
      { id: 'INV-MHG-0915', cells: ['INV-MHG-0915', '01–15 Sep 2026', '42', 'AED 67,840.00', '24 Sep 2026'], status: 'Under review', tone: 'warning' }, { id: 'INV-MHG-0831', cells: ['INV-MHG-0831', '16–31 Aug 2026', '38', 'AED 59,210.00', 'Approved'], status: 'Approved', tone: 'success' }, { id: 'INV-MHG-0815', cells: ['INV-MHG-0815', '01–15 Aug 2026', '35', 'AED 51,995.00', 'Settled'], status: 'Settled', tone: 'success' }], notice: { title: 'Payments are not connected', detail: 'Bank details remain masked. No invoice or payment is processed here.', tone: 'info' } },
  reports: { eyebrow: 'Analytics', title: 'Reports', description: 'Review supplier portfolio, inventory, booking and settlement reporting previews.', action: 'Create report draft', icon: BarChart3,
    stats: [{ label: 'Saved reports', value: '12', detail: 'Across 4 categories' }, { label: 'Scheduled', value: '4', detail: 'Delivery not connected' }, { label: 'Exports this month', value: '18', detail: 'UI preview count' }, { label: 'Data freshness', value: 'Mock', detail: 'No live feed' }], columns: ['Report', 'Category', 'Period', 'Format', 'Last generated'], rows: [
      { id: 'RPT-101', cells: ['Portfolio readiness', 'Hotels & content', 'Current', 'XLSX', '16 Sep 2026'], status: 'Ready', tone: 'success' }, { id: 'RPT-108', cells: ['Availability coverage', 'Inventory', 'Next 90 days', 'CSV', '16 Sep 2026'], status: 'Ready', tone: 'success' }, { id: 'RPT-114', cells: ['Supplier settlement', 'Invoices', 'September 2026', 'PDF', 'Not generated'], status: 'Draft', tone: 'neutral' }], notice: { title: 'Reporting preview only', detail: 'Exports and scheduled delivery are not connected to live supplier data.', tone: 'info' } },
  finance: { eyebrow: 'Settlement workspace', title: 'Finance', description: 'Track statement periods, supplier payables, invoice status and settlement readiness using masked operational data.', action: 'Upload invoice', icon: BadgeDollarSign,
    stats: [{ label: 'Pending settlement', value: 'AED 84,520', detail: '14 bookings' }, { label: 'Next payout', value: '24 Sep', detail: 'UI schedule preview' }, { label: 'Invoices due', value: '3', detail: 'Before 20 Sep' }, { label: 'Disputes', value: '1', detail: 'Under review' }], columns: ['Statement', 'Period', 'Bookings', 'Supplier payable', 'Invoice'], rows: [
      { id: 'STM-2026-09-A', cells: ['September · Cycle A', '01–15 Sep 2026', '42', 'AED 67,840.00', 'INV-MHG-0915'], status: 'Under review', tone: 'warning' }, { id: 'STM-2026-08-B', cells: ['August · Cycle B', '16–31 Aug 2026', '38', 'AED 59,210.00', 'INV-MHG-0831'], status: 'Approved', tone: 'success' }, { id: 'STM-2026-08-A', cells: ['August · Cycle A', '01–15 Aug 2026', '35', 'AED 51,995.00', 'INV-MHG-0815'], status: 'Settled', tone: 'success' }], notice: { title: 'Payments are not connected', detail: 'Bank details remain masked and all balances shown are typed mock data. No invoice or payment is processed here.', tone: 'info' } },
  connectivity: { eyebrow: 'Distribution setup', title: 'Connectivity', description: 'Prepare channel-manager connections, property mappings and delivery logs for future reviewed integrations.', action: 'Request connection', icon: Link2,
    stats: [{ label: 'Connections', value: '0 live', detail: '2 setup drafts' }, { label: 'Properties mapped', value: '9 / 12', detail: 'UI mapping preview' }, { label: 'Room mappings', value: '61 / 74', detail: '13 pending' }, { label: 'Failed deliveries', value: '—', detail: 'No live connector' }], columns: ['Connection', 'Provider', 'Scope', 'Mappings', 'Last activity'], rows: [
      { id: 'CON-001', cells: ['Nexus CRS connection', 'Nexus Channel Connect', '8 properties', '48 rooms', 'Not connected'], status: 'Setup draft', tone: 'neutral' }, { id: 'CON-002', cells: ['Direct hotel API', 'Meridian Hospitality', '4 properties', '26 rooms', 'Not connected'], status: 'Requirements review', tone: 'warning' }], notice: { title: 'No credentials or live API calls', detail: 'This page contains no tokens, raw supplier payloads or production endpoints. Connection actions are UI placeholders only.', tone: 'warning' } },
  team: { eyebrow: 'Workspace controls', title: 'Team & Access', description: 'Preview role-based workspace membership for contracting, inventory, reservations and finance functions.', action: 'Invite team member', icon: UsersRound,
    stats: [{ label: 'Active members', value: '12', detail: 'Across 5 roles' }, { label: 'Pending invites', value: '2', detail: 'Expire in 4 days' }, { label: 'Administrators', value: '2', detail: 'Full workspace access' }, { label: 'Last review', value: '14 Sep', detail: 'Access review date' }], columns: ['Team member', 'Role', 'Property scope', 'Last active', 'MFA'], rows: [
      { id: 'USR-01', cells: ['Aisha Khan', 'Supplier Administrator', 'All properties', 'Now', 'Required'], status: 'Active', tone: 'success' }, { id: 'USR-04', cells: ['Rohan Mehta', 'Contracting Manager', 'UAE portfolio', '32 min ago', 'Required'], status: 'Active', tone: 'success' }, { id: 'USR-09', cells: ['Finance Operations', 'Finance Viewer', 'All properties', 'Yesterday', 'Pending'], status: 'Review access', tone: 'warning' }], notice: { title: 'Authorization remains server-owned', detail: 'These controls do not grant permissions. Final roles and tenant scope must be enforced by authenticated server context.', tone: 'info' } },
  support: { eyebrow: 'Help centre', title: 'Support', description: 'Track operational questions, onboarding assistance and incident history for your supplier workspace.', action: 'Create support request', icon: CircleHelp,
    stats: [{ label: 'Open requests', value: '2', detail: '1 awaiting response' }, { label: 'Resolved this month', value: '8', detail: 'Median 4.2 hours' }, { label: 'Knowledge articles', value: '24', detail: 'Supplier operations' }, { label: 'Service status', value: 'Preview', detail: 'No live monitoring' }], columns: ['Request', 'Category', 'Created', 'Owner', 'Last update'], rows: [
      { id: 'SUP-2841', cells: ['Inventory import guidance', 'Inventory', '15 Sep 2026', 'Supply Operations', '42 min ago'], status: 'Awaiting supplier', tone: 'warning' }, { id: 'SUP-2798', cells: ['Contract validity clarification', 'Contracting', '12 Sep 2026', 'Contracting Desk', 'Yesterday'], status: 'In progress', tone: 'info' }, { id: 'SUP-2710', cells: ['Room mapping review', 'Connectivity', '07 Sep 2026', 'Integration Desk', '10 Sep 2026'], status: 'Resolved', tone: 'success' }] },
  settings: { eyebrow: 'Supplier profile', title: 'Settings', description: 'Review organisation preferences, notification routing, regional formats and workspace defaults.', action: 'Save draft', icon: Settings,
    stats: [{ label: 'Organisation', value: 'Verified', detail: 'Meridian Hospitality' }, { label: 'Default currency', value: 'AED', detail: 'ISO-4217' }, { label: 'Timezone', value: 'UTC+04', detail: 'Asia/Dubai' }, { label: 'Notifications', value: '8 enabled', detail: '3 recipients' }], columns: ['Setting group', 'Owner', 'Last updated', 'Review cycle', 'Scope'], rows: [
      { id: 'SET-01', cells: ['Organisation profile', 'Supplier Administrator', '14 Sep 2026', 'Annual', 'Workspace'], status: 'Verified', tone: 'success' }, { id: 'SET-02', cells: ['Operational notifications', 'Reservations Manager', '16 Sep 2026', 'Quarterly', 'All properties'], status: 'Configured', tone: 'success' }, { id: 'SET-03', cells: ['Settlement preferences', 'Finance Administrator', '10 Sep 2026', 'Quarterly', 'Finance'], status: 'Review due', tone: 'warning' }] },
} satisfies Record<string, ModuleConfig>
