import Link from 'next/link'
import { ArrowUpRight, Check, ChevronRight, Globe2, Network, ShieldCheck, Zap } from 'lucide-react'

export const navItems = [
  { label: 'Solutions', href: '/solutions' },
  { label: 'Platform', href: '/platform' },
  { label: 'Inventory', href: '/inventory' },
  { label: 'Resources', href: '/resources' },
  { label: 'Company', href: '/about' },
]

export function Logo() { return <Link href="/" className="flex items-center gap-3" aria-label="FBEDS home"><span className="flex size-9 items-center justify-center rounded-[4px] bg-brand text-lg font-black text-white">F</span><span className="text-xl font-extrabold tracking-[-.06em]">FBEDS<span className="text-brand">.</span></span></Link> }

export function Header() { return <header className="border-b border-border bg-white/90 backdrop-blur-sm"><div className="container-wide flex min-h-20 items-center justify-between gap-6"><Logo /><nav className="hidden items-center gap-7 text-sm font-semibold text-ink-muted lg:flex">{navItems.map((item) => <Link key={item.href} href={item.href} className="transition-colors hover:text-brand">{item.label}</Link>)}</nav><div className="flex items-center gap-3"><Link href="/login" className="hidden text-sm font-semibold text-ink-muted sm:block">Sign in</Link><Link href="/request-demo" className="inline-flex items-center gap-2 rounded-[4px] bg-brand px-4 py-2.5 text-sm font-bold text-white transition-colors hover:bg-brand-dark">Request a demo <ArrowUpRight size={15} /></Link></div></div></header> }

export function Footer() { return <footer className="border-t border-border bg-ink text-white"><div className="container-wide grid gap-10 py-12 md:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><Logo /><p className="mt-5 max-w-xs text-sm leading-6 text-white/60">The infrastructure layer for modern hotel distribution.</p></div><div><p className="footer-label">Explore</p><div className="mt-4 flex flex-col gap-3 text-sm text-white/70"><Link href="/solutions">Solutions</Link><Link href="/platform">Platform</Link><Link href="/inventory">Inventory</Link><Link href="/resources">Resources</Link></div></div><div><p className="footer-label">Company</p><div className="mt-4 flex flex-col gap-3 text-sm text-white/70"><Link href="/about">About FBEDS</Link><Link href="/careers">Careers</Link><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link></div></div><div><p className="footer-label">Portals</p><div className="mt-4 flex flex-col gap-3 text-sm text-white/70"><Link href="/agent">Agent portal</Link><Link href="/supplier">Supplier portal</Link><Link href="/admin">Operations</Link></div></div></div><div className="container-wide flex flex-col gap-3 border-t border-white/10 py-5 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 FBEDS. Built for better distribution.</span><span>fbeds-website.vercel.app</span></div></footer> }

export function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="max-w-2xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 text-balance text-3xl font-extrabold tracking-[-.045em] text-ink sm:text-5xl">{title}</h2>{text && <p className="mt-5 text-pretty text-lg leading-7 text-ink-muted">{text}</p>}</div> }

export function CTA() { return <section className="container-wide py-20"><div className="relative overflow-hidden rounded-[6px] bg-ink px-7 py-12 text-white sm:px-12 lg:flex lg:items-end lg:justify-between"><div className="absolute right-0 top-0 h-full w-1/2 bg-[linear-gradient(135deg,transparent_0%,rgba(217,4,41,.3)_100%)]" /><div className="relative max-w-2xl"><p className="eyebrow text-coral-soft">Build the next connection</p><h2 className="mt-4 text-balance text-3xl font-extrabold tracking-[-.045em] sm:text-5xl">Make hotel distribution a growth advantage.</h2><p className="mt-5 max-w-xl text-lg leading-7 text-white/65">Tell us where you are today. We&apos;ll show you what a better operating layer could look like.</p></div><Link href="/request-demo" className="relative mt-8 inline-flex items-center gap-2 rounded-[4px] bg-brand px-5 py-3.5 text-sm font-bold text-white hover:bg-brand-dark lg:mt-0">Talk to FBEDS <ArrowUpRight size={16} /></Link></div></section> }

export function NetworkVisual() { return <div className="relative min-h-[410px] overflow-hidden rounded-[6px] border border-border bg-panel p-5 shadow-[0_22px_60px_rgba(31,41,55,.08)]"><div className="absolute inset-0 grid-lines opacity-70" /><div className="relative flex items-center justify-between text-[10px] font-bold uppercase tracking-[.14em] text-ink-muted"><span>FBEDS network</span><span className="flex items-center gap-1.5 text-trust"><span className="size-1.5 rounded-full bg-trust" /> Live infrastructure</span></div><svg viewBox="0 0 500 330" className="relative mt-5 h-[310px] w-full" role="img" aria-label="FBEDS connecting hotels, suppliers, buyers and booking technology"><path d="M110 80 C190 80, 190 155, 250 165 S330 105, 390 85 M110 250 C180 250, 190 175, 250 165 S325 220, 390 250" fill="none" stroke="#d1d5db" strokeWidth="2"/><path d="M110 80 C190 80, 190 155, 250 165 S330 105, 390 85" fill="none" stroke="#10b981" strokeWidth="2" className="network-line"/><path d="M110 250 C180 250, 190 175, 250 165 S325 220, 390 250" fill="none" stroke="#d90429" strokeWidth="2" className="network-line"/><circle cx="250" cy="165" r="42" fill="#1f2937"/><text x="250" y="161" fill="white" fontSize="14" fontWeight="800" textAnchor="middle">FBEDS</text><text x="250" y="178" fill="#a7f3d0" fontSize="9" fontWeight="700" textAnchor="middle">CONTROL LAYER</text>{[['Hotels',110,80,'#d90429'],['Suppliers',110,250,'#10b981'],['Buyers',390,85,'#d90429'],['Booking tech',390,250,'#10b981']].map(([label,x,y,color]) => <g key={String(label)}><circle cx={x as number} cy={y as number} r="27" fill="white" stroke={color as string} strokeWidth="2"/><text x={x as number} y={(y as number)+4} fill="#1f2937" fontSize="10" fontWeight="700" textAnchor="middle">{label as string}</text></g>)}</svg></div> }

export const capabilities = [{ icon: Globe2, title: 'Global hotel inventory', text: 'Aggregate contracted and dynamic supply into one dependable source of truth.' }, { icon: Zap, title: 'Real-time distribution', text: 'Move availability, rates and bookings at the speed your buyers expect.' }, { icon: Network, title: 'Smarter connectivity', text: 'Connect suppliers and buyers through modern API and XML infrastructure.' }, { icon: ShieldCheck, title: 'Booking confidence', text: 'Build every transaction on clear content, resilient workflows and control.' }]
export const audiences = ['Travel agencies', 'Tour operators', 'DMCs', 'Hotels', 'OTAs & travel tech']

export function PageFrame({ children }: { children: React.ReactNode }) { return <div className="site-shell"><Header /><main>{children}</main><Footer /></div> }
export function PortalFrame({ kind, children }: { kind: string; children: React.ReactNode }) { return <div className="min-h-screen bg-panel"><header className="border-b border-border bg-white"><div className="container-wide flex h-20 items-center justify-between"><Logo /><span className="rounded-full border border-border px-3 py-1 text-xs font-bold uppercase tracking-[.12em] text-ink-muted">{kind} portal</span></div></header>{children}</div> }
export function BulletList({ items }: { items: string[] }) { return <div className="flex flex-col gap-4">{items.map((item) => <div key={item} className="flex gap-3 text-sm font-semibold text-ink"><Check size={18} className="shrink-0 text-trust" />{item}</div>)}</div> }
export function LinkButton({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex items-center gap-2 rounded-[4px] bg-brand px-5 py-3.5 text-sm font-bold text-white hover:bg-brand-dark">{children}<ArrowUpRight size={16} /></Link> }
export function MoreLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex items-center gap-2 text-sm font-bold text-brand hover:text-brand-dark">{children}<ChevronRight size={16} /></Link> }

export const pageCopy: Record<string, { eyebrow: string; title: string; intro: string; bullets: string[] }> = {
  solutions: { eyebrow: 'Solutions', title: 'A stronger operating layer for every side of hotel distribution.', intro: 'Connect supply, demand and technology through a platform designed around the real complexity of B2B travel.', bullets: ['Travel seller connectivity', 'Supplier distribution', 'Travel technology infrastructure'] },
  platform: { eyebrow: 'Platform', title: 'The control layer between inventory and demand.', intro: 'Bring content, rates, availability and booking workflows together through clear, resilient infrastructure.', bullets: ['API-first architecture', 'Structured hotel content', 'Reliable booking workflows'] },
  inventory: { eyebrow: 'Inventory', title: 'One operating view for a world of hotel supply.', intro: 'Organise contracted and dynamic inventory so teams can move faster, make better decisions and distribute with confidence.', bullets: ['Contracted and dynamic supply', 'Rate and availability controls', 'Buyer-ready hotel content'] },
  about: { eyebrow: 'The company', title: 'The connected layer behind better hotel distribution.', intro: 'FBEDS is building the operating infrastructure that helps hospitality businesses connect inventory, demand and technology with less friction.', bullets: ['Built for the complexity of B2B travel', 'Designed around dependable connectivity', 'Focused on measurable outcomes'] },
  resources: { eyebrow: 'Resources', title: 'Practical thinking for modern hotel distribution.', intro: 'Explore perspectives on connectivity, inventory operations and the commercial systems shaping B2B travel.', bullets: ['Distribution strategy', 'Hotel technology', 'Commercial operations'] },
  contact: { eyebrow: 'Contact', title: 'Let&apos;s talk about what you are building.', intro: 'Whether you distribute rooms, source inventory or connect a travel product, the FBEDS team is ready to understand your goals.', bullets: ['Tell us about your business', 'Find the right FBEDS solution', 'Plan your next connection'] },
}

export function ContentPage({ page }: { page: keyof typeof pageCopy }) { const copy = pageCopy[page]; return <PageFrame><section className="container-wide py-16 lg:py-24"><div className="grid gap-12 lg:grid-cols-[1fr_.68fr] lg:items-start"><div><p className="eyebrow">{copy.eyebrow}</p><h1 className="mt-4 max-w-3xl text-balance text-5xl font-extrabold leading-[1.03] tracking-[-.06em] text-ink sm:text-7xl">{copy.title}</h1><p className="mt-7 max-w-2xl text-pretty text-lg leading-8 text-ink-muted">{copy.intro}</p><LinkButton href="/request-demo">Start a conversation</LinkButton></div><div className="h-fit border border-border bg-panel p-7"><p className="text-xs font-bold uppercase tracking-[.14em] text-ink-muted">What to expect</p><div className="mt-6"><BulletList items={copy.bullets} /></div></div></div></section><CTA /></PageFrame> }

export function PortalLinks() { return <div className="mt-8 flex flex-wrap gap-3"><Link href="/agent" className="rounded-[4px] border border-border-strong bg-white px-4 py-3 text-sm font-bold">Agent portal</Link><Link href="/supplier" className="rounded-[4px] border border-border-strong bg-white px-4 py-3 text-sm font-bold">Supplier portal</Link><Link href="/admin" className="rounded-[4px] border border-border-strong bg-white px-4 py-3 text-sm font-bold">Operations portal</Link></div> }

export { ArrowUpRight }
