-- Maker-checker approval requests (ADR 0016). Foundation only: nothing in the API consumes this table yet.
-- A request records who asked for a sensitive action and who decided it. It never executes the action.
-- Integrity is enforced here as well as in the service: a decider can never be the requester,
-- and a decided request always carries a decider and a decision time.
-- No guest PII, credentials or raw supplier payloads are stored; before/after state is minimal.
--
-- Tenant indexes: (tenant_id, status) for approval queues, (tenant_id, entity_type, entity_id) for an
-- entity's approval history. The (tenant_id, action, request_id) unique key makes requests idempotent.
--
-- The conditional GRANT below mirrors "SupplierMutation". It is part of this migration but it is a
-- production privilege change in effect, so it needs the ADR 0013 human decision before this migration
-- is applied to any persistent environment.
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP POLICY IF EXISTS "ApprovalRequest_tenant_isolation" ON "ApprovalRequest";
--   DROP TABLE IF EXISTS "ApprovalRequest";
--   DROP TYPE IF EXISTS "ApprovalRequestStatus";

-- CreateEnum
CREATE TYPE "ApprovalRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

-- CreateTable
CREATE TABLE "ApprovalRequest" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT NOT NULL,
    "request_id" TEXT NOT NULL,
    "status" "ApprovalRequestStatus" NOT NULL DEFAULT 'PENDING',
    "requested_by_id" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "before_state" JSONB,
    "proposed_state" JSONB,
    "decided_by_id" TEXT,
    "decided_at" TIMESTAMP(3),
    "decision_reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ApprovalRequest_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ApprovalRequest_separation_of_duties" CHECK ("decided_by_id" IS NULL OR "decided_by_id" <> "requested_by_id"),
    CONSTRAINT "ApprovalRequest_decision_complete" CHECK (
      ("status" = 'PENDING' AND "decided_by_id" IS NULL AND "decided_at" IS NULL)
      OR ("status" = 'CANCELLED')
      OR ("status" IN ('APPROVED', 'REJECTED') AND "decided_by_id" IS NOT NULL AND "decided_at" IS NOT NULL)
    )
);

-- CreateIndex
CREATE INDEX "ApprovalRequest_tenant_id_status_idx" ON "ApprovalRequest"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "ApprovalRequest_tenant_id_entity_type_entity_id_idx" ON "ApprovalRequest"("tenant_id", "entity_type", "entity_id");

-- CreateIndex
CREATE UNIQUE INDEX "ApprovalRequest_tenant_id_action_request_id_key" ON "ApprovalRequest"("tenant_id", "action", "request_id");

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ApprovalRequest" ADD CONSTRAINT "ApprovalRequest_decided_by_id_fkey" FOREIGN KEY ("decided_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ApprovalRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApprovalRequest" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ApprovalRequest_tenant_isolation" ON "ApprovalRequest"
  USING ("tenant_id" = "fbeds_current_tenant_id"())
  WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "ApprovalRequest" TO fbeds_api';
  END IF;
END $$;
