import Link from 'next/link'
import { ArrowLeft, ArrowRight, Building2, Check, FileCheck, Image, MapPin } from 'lucide-react'
import { PageHeader } from '../../../../components/ui/PageHeader'

export default function NewHotelPage() {
  return <div className="supplier-page"><Link className="back-link" href="/hotels"><ArrowLeft size={12} /> Back to hotels</Link><PageHeader eyebrow="Hotel onboarding · Draft" title="Add a hotel" description="Create a structured hotel draft. Nothing is distributed until reviewed backend workflows and approvals are connected." />
    <div className="wizard-steps"><span className="active"><i>1</i><strong>Supply type</strong></span><span><i>2</i><strong>Core details</strong></span><span><i>3</i><strong>Rooms & content</strong></span><span><i>4</i><strong>Commercial setup</strong></span><span><i>5</i><strong>Review</strong></span></div>
    <div className="wizard-layout"><section className="panel wizard-card"><p className="page-eyebrow"><i />STEP 1 OF 5</p><h2>How is this hotel supplied?</h2><p>Select the onboarding path. The workspace adapts the next steps for direct hotel, DMC portfolio or channel-manager mapping.</p><div className="supplier-type-grid"><button className="selected"><Building2 size={23} /><strong>Hotel / property</strong><small>Add one hotel, resort or serviced apartment.</small><i><Check size={12} /></i></button><button><MapPin size={23} /><strong>DMC / local operator</strong><small>Onboard a contracted hotel from a DMC portfolio.</small></button><button><FileCheck size={23} /><strong>Channel manager</strong><small>Prepare hotel and room mappings for review.</small></button></div><div className="wizard-actions"><Link className="btn" href="/hotels">Cancel</Link><button className="btn btn-primary">Continue <ArrowRight size={13} /></button></div></section><aside className="panel wizard-help"><span><Image size={21} /></span><h3>Before you begin</h3><p>Prepare hotel identity, location, contacts, room definitions, photos, facilities, policies and commercial documents.</p><ul><li>Drafts remain private</li><li>No live API publication</li><li>No credentials required</li></ul></aside></div>
  </div>
}
