-- Authoritative inventory and allotment foundation (ADR 0030).
--
-- Adds, as forward-only DDL: explicit inventory modes (ALLOTMENT, FREE_SALE, ON_REQUEST, CLOSED), shared inventory pools with
-- per-night counters, plan membership of a pool, a hotel-local release time, inventory provenance and freshness, and the counter
-- kind recorded on each held night so release, confirmation and cancellation always return to the counter the stock was taken from.
--
-- Existing rows: every DailyAvailability row becomes mode ALLOTMENT, source ADMIN, received_at = migration time and fresh_until NULL
-- (never expires), which is exactly how it behaved before. Every existing InventoryHoldNight is counter_kind PLAN_ROW. Every existing
-- RatePlan gets release_time_local '00:00' and no pool. No existing row changes meaning and nothing is backfilled or guessed.
--
-- Integrity beyond Prisma:
--   * InventoryPoolDay: capacity, sold, held >= 0 and sold + held <= capacity (stock can never go negative or oversell).
--   * Pool name is non-empty and the archived timestamp agrees with the status.
--   * RatePlan.release_time_local is HH:MM 24h; release_days stays >= 0.
--   * InventoryHoldNight: counter_kind POOL_DAY requires pool_day_id and the others forbid it.
--   * DailyAvailability: fresh_until, when set, is after received_at.
--   * A trigger refuses a rate plan in a pool of another hotel or another supplier, or in an archived pool, or a pool plan whose
--     room belongs to another hotel. Tenant mixing is already impossible through the composite foreign keys.
--
-- Tenant indexes: tenant_id leads every non-unique index and every unique key that is used for tenant-scoped lookup.
-- Concurrency: stock is changed only by guarded single-statement UPDATEs (see inventory-counters.ts); the CHECK is the backstop.
--
-- The conditional GRANTs mirror earlier migrations (ADR 0013): they are production privilege changes in effect and need the human
-- decision before this migration is applied to any persistent environment. The restricted hold-expiry role is provisioned by code
-- (hold-expiry-role.ts), which this change extends for the pool-day counter.
--
-- Rollback is a later forward migration; do not edit this file after it is applied. Before dropping, release every pool
-- (set RatePlan.inventory_pool_id to NULL) and note that pool-day stock history would be lost:
--   ALTER TABLE "InventoryHoldNight" DROP COLUMN "pool_day_id", DROP COLUMN "counter_kind";
--   ALTER TABLE "RatePlan" DROP COLUMN "inventory_pool_id", DROP COLUMN "release_time_local";
--   ALTER TABLE "DailyAvailability" DROP COLUMN "inventory_mode", DROP COLUMN "source", DROP COLUMN "received_at", DROP COLUMN "fresh_until";
--   DROP TABLE "InventoryPoolDay", "InventoryPool"; DROP TYPE "InventoryCounterKind", "InventoryPoolStatus", "InventorySource", "InventoryMode";

-- CreateEnum
CREATE TYPE "InventoryMode" AS ENUM ('ALLOTMENT', 'FREE_SALE', 'ON_REQUEST', 'CLOSED');
-- CreateEnum
CREATE TYPE "InventorySource" AS ENUM ('CONTRACT', 'ADMIN', 'SUPPLIER_API', 'SUPPLIER_FEED', 'SYSTEM');
-- CreateEnum
CREATE TYPE "InventoryPoolStatus" AS ENUM ('ACTIVE', 'ARCHIVED');
-- CreateEnum
CREATE TYPE "InventoryCounterKind" AS ENUM ('PLAN_ROW', 'POOL_DAY', 'NONE');
-- AlterTable
ALTER TABLE "DailyAvailability" ADD COLUMN     "fresh_until" TIMESTAMP(3),
ADD COLUMN     "inventory_mode" "InventoryMode" NOT NULL DEFAULT 'ALLOTMENT',
ADD COLUMN     "received_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "source" "InventorySource" NOT NULL DEFAULT 'ADMIN';
-- AlterTable
ALTER TABLE "InventoryHoldNight" ADD COLUMN     "counter_kind" "InventoryCounterKind" NOT NULL DEFAULT 'PLAN_ROW',
ADD COLUMN     "pool_day_id" TEXT;
-- AlterTable
ALTER TABLE "RatePlan" ADD COLUMN     "inventory_pool_id" TEXT,
ADD COLUMN     "release_time_local" CHAR(5) NOT NULL DEFAULT '00:00';
-- CreateTable
CREATE TABLE "InventoryPool" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "supplier_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "InventoryPoolStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_by_id" TEXT NOT NULL,
    "archived_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "InventoryPool_pkey" PRIMARY KEY ("id")
);
-- CreateTable
CREATE TABLE "InventoryPoolDay" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "pool_id" TEXT NOT NULL,
    "stay_date" DATE NOT NULL,
    "capacity" INTEGER NOT NULL,
    "sold" INTEGER NOT NULL DEFAULT 0,
    "held" INTEGER NOT NULL DEFAULT 0,
    "source" "InventorySource" NOT NULL DEFAULT 'ADMIN',
    "source_updated_at" TIMESTAMP(3),
    "received_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fresh_until" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "InventoryPoolDay_pkey" PRIMARY KEY ("id")
);
-- CreateIndex
CREATE INDEX "InventoryPool_tenant_id_hotel_id_idx" ON "InventoryPool"("tenant_id", "hotel_id");
-- CreateIndex
CREATE UNIQUE INDEX "InventoryPool_tenant_id_id_key" ON "InventoryPool"("tenant_id", "id");
-- CreateIndex
CREATE UNIQUE INDEX "InventoryPool_tenant_id_hotel_id_supplier_id_name_key" ON "InventoryPool"("tenant_id", "hotel_id", "supplier_id", "name");
-- CreateIndex
CREATE INDEX "InventoryPoolDay_tenant_id_stay_date_idx" ON "InventoryPoolDay"("tenant_id", "stay_date");
-- CreateIndex
CREATE UNIQUE INDEX "InventoryPoolDay_pool_id_stay_date_key" ON "InventoryPoolDay"("pool_id", "stay_date");
-- CreateIndex
CREATE UNIQUE INDEX "InventoryPoolDay_tenant_id_id_key" ON "InventoryPoolDay"("tenant_id", "id");
-- CreateIndex
CREATE INDEX "RatePlan_tenant_id_inventory_pool_id_idx" ON "RatePlan"("tenant_id", "inventory_pool_id");
-- AddForeignKey
ALTER TABLE "RatePlan" ADD CONSTRAINT "RatePlan_tenant_id_inventory_pool_id_fkey" FOREIGN KEY ("tenant_id", "inventory_pool_id") REFERENCES "InventoryPool"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "InventoryPool" ADD CONSTRAINT "InventoryPool_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "InventoryPool" ADD CONSTRAINT "InventoryPool_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "InventoryPool" ADD CONSTRAINT "InventoryPool_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "InventoryPoolDay" ADD CONSTRAINT "InventoryPoolDay_tenant_id_pool_id_fkey" FOREIGN KEY ("tenant_id", "pool_id") REFERENCES "InventoryPool"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
-- AddForeignKey
ALTER TABLE "InventoryHoldNight" ADD CONSTRAINT "InventoryHoldNight_tenant_id_pool_day_id_fkey" FOREIGN KEY ("tenant_id", "pool_day_id") REFERENCES "InventoryPoolDay"("tenant_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- Integrity constraints
ALTER TABLE "InventoryPoolDay" ADD CONSTRAINT "InventoryPoolDay_stock_check"
  CHECK ("capacity" >= 0 AND "sold" >= 0 AND "held" >= 0 AND "sold" + "held" <= "capacity"),
  ADD CONSTRAINT "InventoryPoolDay_fresh_after_received" CHECK ("fresh_until" IS NULL OR "fresh_until" > "received_at");

ALTER TABLE "InventoryPool" ADD CONSTRAINT "InventoryPool_name_check" CHECK (char_length(btrim("name")) BETWEEN 1 AND 80 AND "name" = btrim("name")),
  ADD CONSTRAINT "InventoryPool_archive_check" CHECK (("status" = 'ARCHIVED') = ("archived_at" IS NOT NULL));

ALTER TABLE "RatePlan" ADD CONSTRAINT "RatePlan_release_time_check" CHECK ("release_time_local" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  ADD CONSTRAINT "RatePlan_release_days_check" CHECK ("release_days" >= 0);

ALTER TABLE "InventoryHoldNight" ADD CONSTRAINT "InventoryHoldNight_counter_check"
  CHECK (("counter_kind" = 'POOL_DAY') = ("pool_day_id" IS NOT NULL));

ALTER TABLE "DailyAvailability" ADD CONSTRAINT "DailyAvailability_fresh_after_received" CHECK ("fresh_until" IS NULL OR "fresh_until" > "received_at");

-- A rate plan may join only an ACTIVE pool of its own hotel and its own supplier.
CREATE OR REPLACE FUNCTION "fbeds_rate_plan_pool_consistency"() RETURNS trigger AS $$
DECLARE
  pool_hotel TEXT; pool_supplier TEXT; pool_state "InventoryPoolStatus";
  plan_hotel TEXT; plan_supplier TEXT;
BEGIN
  IF NEW."inventory_pool_id" IS NULL THEN RETURN NEW; END IF;
  SELECT "hotel_id", "supplier_id", "status" INTO pool_hotel, pool_supplier, pool_state
    FROM "InventoryPool" WHERE "id" = NEW."inventory_pool_id" AND "tenant_id" = NEW."tenant_id";
  IF NOT FOUND THEN RAISE EXCEPTION 'inventory pool not found for this tenant' USING ERRCODE = '23514'; END IF;
  SELECT "hotel_id" INTO plan_hotel FROM "RoomType" WHERE "id" = NEW."room_type_id";
  SELECT "supplier_id" INTO plan_supplier FROM "Contract" WHERE "id" = NEW."contract_id" AND "tenant_id" = NEW."tenant_id";
  IF plan_hotel IS DISTINCT FROM pool_hotel THEN RAISE EXCEPTION 'rate plan and inventory pool belong to different hotels' USING ERRCODE = '23514'; END IF;
  IF plan_supplier IS DISTINCT FROM pool_supplier THEN RAISE EXCEPTION 'rate plan and inventory pool belong to different suppliers' USING ERRCODE = '23514'; END IF;
  IF pool_state <> 'ACTIVE' AND (TG_OP = 'INSERT' OR OLD."inventory_pool_id" IS DISTINCT FROM NEW."inventory_pool_id") THEN
    RAISE EXCEPTION 'inventory pool is archived' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER "RatePlan_pool_consistency" BEFORE INSERT OR UPDATE OF "inventory_pool_id", "room_type_id", "contract_id" ON "RatePlan"
  FOR EACH ROW EXECUTE FUNCTION "fbeds_rate_plan_pool_consistency"();

-- Row-level security: tenant isolation on both new tables.
ALTER TABLE "InventoryPool" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryPool" FORCE ROW LEVEL SECURITY;
CREATE POLICY "InventoryPool_tenant_isolation" ON "InventoryPool" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "InventoryPoolDay" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryPoolDay" FORCE ROW LEVEL SECURITY;
CREATE POLICY "InventoryPoolDay_tenant_isolation" ON "InventoryPoolDay" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "InventoryPool" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "InventoryPoolDay" TO fbeds_api';
  END IF;
END $$;
