'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Bell, ChevronDown, Hotel, LogOut, Menu, ShieldCheck, UserCircle, X } from 'lucide-react'
import { useState } from 'react'
import { adminSections, demoSession, demoTenants } from '@/lib/architecture'

const icons = { LayoutDashboard: '▦', Building2: '⌂', ShieldCheck: '◈', Hotel: '▣', Network: '⌁', ScrollText: '≡' }
export function AdminShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [mobileOpen, setMobileOpen] = useState(false); const [tenant, setTenant] = useState(demoTenants[0]); const [tenantOpen, setTenantOpen] = useState(false)
  return <div className="enterprise-shell"><aside className={`enterprise-sidebar ${mobileOpen ? 'open' : ''}`}><div className="enterprise-brand"><span className="enterprise-mark"><Hotel size={17} /></span><span><strong>bedbank</strong><small>CONTROL PLANE</small></span><button className="sidebar-close" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={17} /></button></div><div className="context-switcher"><button className="context-button" onClick={() => setTenantOpen(!tenantOpen)}><span className="context-avatar">{tenant.name.slice(0,1)}</span><span><small>ACTIVE CONTEXT</small><strong>{tenant.name}</strong></span><ChevronDown size={14} /></button>{tenantOpen && <div className="context-menu">{demoTenants.map((item) => <button key={item.id} onClick={() => { setTenant(item); setTenantOpen(false) }}><span>{item.name}</span><small>{item.code}</small></button>)}</div>}</div><div className="shell-caption">ADMIN / EXTRANET</div><nav className="enterprise-nav" aria-label="Admin navigation">{adminSections.map((item) => <Link key={item.href} href={item.href} onClick={() => setMobileOpen(false)} className={pathname === item.href ? 'active' : ''}><span className="nav-glyph">{icons[item.icon]}</span>{item.label}{item.href === '/admin' && <i />}</Link>)}</nav><div className="sidebar-footer"><div className="security-note"><ShieldCheck size={15} /><span><strong>Tenant isolation</strong><small>Policy engine active</small></span></div><div className="session-user"><span className="user-initials">JD</span><span><strong>{demoSession.user.name}</strong><small>Platform Admin</small></span><button aria-label="User menu"><UserCircle size={16} /></button></div></div></aside><main className="enterprise-main"><header className="enterprise-topbar"><button className="mobile-nav-trigger" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={18} /></button><div className="shell-breadcrumb"><span>Platform</span><b>/</b><strong>{pathname === '/admin' ? 'Overview' : pathname.split('/').pop()?.replace('-', ' ')}</strong></div><div className="topbar-actions"><span className="runtime-badge"><i /> Preview environment</span><button aria-label="Notifications"><Bell size={17} /><em /></button><span className="top-user">JD</span></div></header>{children}</main></div>
}
