'use client'

import { useMemo, useState } from 'react'
import { Bell, CalendarDays, Check, ChevronDown, CircleHelp, Eye, Filter, Heart, Info, MapPin, Search, SlidersHorizontal, Star, Users, Wifi, X } from 'lucide-react'

type Hotel = { id: string; name: string; city: string; stars: number; rating: number; price: number; rooms: number; supplier: string; board: string; tone: string; amenities: string[]; distance: string; reviews: number }

const hotels: Hotel[] = [
  { id: 'HTL-000182', name: 'One&Only Royal Mirage', city: 'Jumeirah Beach Dubai', stars: 5, rating: 4.9, price: 820, rooms: 12, supplier: 'Hotelbeds', board: 'Breakfast included', tone: 'sand', amenities: ['Private Beach', 'Luxury Spa', 'WiFi'], distance: '4.2 km from city', reviews: 4927 },
  { id: 'HTL-000241', name: 'Nikki Beach Resort & Spa Dubai', city: 'Pearl Jumeirah, Dubai', stars: 5, rating: 4.8, price: 690, rooms: 8, supplier: 'WebBeds', board: 'Room only', tone: 'blue', amenities: ['Beach Club', 'Spa', 'WiFi'], distance: '2.1 km from city', reviews: 3421 },
  { id: 'HTL-000319', name: 'One&Only One Za’abeel', city: 'Za’abeel 1, Dubai', stars: 5, rating: 4.7, price: 540, rooms: 6, supplier: 'Direct contract', board: 'Half board', tone: 'teal', amenities: ['Restaurant', 'Pool', 'WiFi'], distance: '7.8 km from city', reviews: 2156 },
  { id: 'HTL-000401', name: 'Palace Downtown', city: 'Downtown Dubai', stars: 5, rating: 4.9, price: 760, rooms: 14, supplier: 'Hotelbeds', board: 'Bed & breakfast', tone: 'rose', amenities: ['Rooftop Pool', 'Dining', 'WiFi'], distance: '3.5 km from city', reviews: 5341 },
  { id: 'HTL-000502', name: 'Kempinski Mall Of The Emirates', city: 'Al Barsha, Dubai', stars: 5, rating: 4.6, price: 695, rooms: 10, supplier: 'WebBeds', board: 'All-inclusive', tone: 'gold', amenities: ['Ski Access', 'Spa', 'WiFi'], distance: '12.3 km from city', reviews: 2718 },
]

export function AgentPortal() {
  const [query, setQuery] = useState('Dubai')
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [stars, setStars] = useState(0)
  const [instant, setInstant] = useState(false)
  const [selected, setSelected] = useState<Hotel | null>(null)
  const [toast, setToast] = useState('')
  const [sort, setSort] = useState('Recommended')
  const [compared, setCompared] = useState<Set<string>>(new Set())
  const [liked, setLiked] = useState<Set<string>>(new Set())
  const [priceRange, setPriceRange] = useState<[number, number]>([0, 1000])
  const [selectedBoard, setSelectedBoard] = useState<string | null>(null)

  const results = useMemo(() => hotels.filter((hotel) => {
    const textMatch = !query || `${hotel.name} ${hotel.city}`.toLowerCase().includes(query.toLowerCase())
    return textMatch && (!stars || hotel.stars >= stars) && (!instant || hotel.rooms >= 8) && hotel.price >= priceRange[0] && hotel.price <= priceRange[1] && (!selectedBoard || hotel.board === selectedBoard)
  }).sort((a, b) => sort === 'Lowest price' ? a.price - b.price : b.rating - a.rating), [query, stars, instant, sort, priceRange, selectedBoard])

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const toggleSet = (set: Set<string>, id: string) => set.has(id) ? new Set([...set].filter((item) => item !== id)) : new Set([...set, id])
  const clearFilters = () => { setStars(0); setInstant(false); setPriceRange([0, 1000]); setSelectedBoard(null) }

  return <div className="hotel-results-app">
    <header className="hotel-topbar">
      <div className="hotel-brand"><span className="hotel-brand-mark" aria-hidden="true">f</span><div><strong>fBeds</strong><small>WHOLESALE TRAVEL</small></div></div>
      <div className="hotel-top-search"><Search size={15} /><input aria-label="Global search" placeholder="Search hotels, bookings or guests" /><kbd>⌘ K</kbd></div>
      <div className="hotel-top-actions"><span className="hotel-live"><i /> LIVE INVENTORY</span><button onClick={() => notify('You have 3 new notifications')} aria-label="Notifications"><Bell size={17} /><b /></button><button onClick={() => notify('Help center opened')} aria-label="Help"><CircleHelp size={17} /></button><span className="hotel-avatar">JD</span><span className="hotel-user-name">Jordan Davis <ChevronDown size={13} /></span></div>
    </header>
    <main className="hotel-main">
      <div className="hotel-breadcrumb"><span>fBeds Getaways</span><b>/</b><strong>Search hotels</strong></div>
      <section className="hotel-page-heading"><div><span className="hotel-eyebrow">LIVE INVENTORY · DUBAI</span><h1>Search hotels</h1><p>Compare live wholesale rates, policies and supplier benefits.</p></div><button className="hotel-help" onClick={() => notify('Help center opened')}><CircleHelp size={15} /> Need help?</button></section>
      <section className="hotel-search-panel"><div className="hotel-search-row"><label className="wide"><span>DESTINATION, HOTEL OR GIATA</span><div><MapPin size={15} /><input aria-label="Destination" value={query} onChange={(e) => setQuery(e.target.value)} /><Info size={13} /></div></label><label><span>CHECK-IN</span><div><CalendarDays size={15} /><input aria-label="Check-in" value="09 Sep 2026" readOnly /></div></label><label><span>CHECK-OUT</span><div><CalendarDays size={15} /><input aria-label="Check-out" value="10 Sep 2026" readOnly /></div></label><label><span>ROOMS & GUESTS</span><div><Users size={15} /><input aria-label="Rooms and guests" value="1 room · 2 guests" readOnly /></div></label><button className="hotel-search-button" onClick={() => notify(`${results.length * 24} properties found`)}><Search size={16} /> Search</button></div><div className="hotel-search-footer"><span><i /> Connected to 4 suppliers · Net rates enabled</span><button onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={14} /> Advanced filters <ChevronDown size={13} /></button></div>{filtersOpen && <div className="hotel-filter-drawer"><button className={stars === 5 ? 'chosen' : ''} onClick={() => setStars(stars === 5 ? 0 : 5)}><Star size={13} /> 5 stars</button><button className={instant ? 'chosen' : ''} onClick={() => setInstant(!instant)}><Check size={13} /> Instant confirmation</button><button onClick={clearFilters}>Clear all</button></div>}</section>
      <div className="hotel-result-layout">
        <aside className="hotel-filters"><div className="hotel-filter-heading"><strong>Filter your results</strong><Filter size={15} /></div><div className="hotel-filter-group"><span>PRICE PER NIGHT</span><div className="hotel-price-range"><input type="range" min="0" max="1000" value={priceRange[0]} onChange={(e) => setPriceRange([Number(e.target.value), priceRange[1]])} /><input type="range" min="0" max="1000" value={priceRange[1]} onChange={(e) => setPriceRange([priceRange[0], Number(e.target.value)])} /><b>AED {priceRange[0]} — AED {priceRange[1]}</b></div></div><div className="hotel-filter-group"><span>SUPPLIER</span>{['All suppliers', 'Hotelbeds', 'WebBeds', 'Direct contract'].map((item, i) => <label key={item}><input type="checkbox" defaultChecked={i === 0} /> {item}<em>{i === 0 ? 120 : 24}</em></label>)}</div><div className="hotel-filter-group"><span>STAR RATING</span>{[5, 4, 3].map((item) => <label key={item}><input type="checkbox" checked={stars === item} onChange={() => setStars(stars === item ? 0 : item)} /> <b className="filter-stars">{'★'.repeat(item)}</b></label>)}</div><div className="hotel-filter-group"><span>BOARD BASIS</span>{['Room only', 'Breakfast included', 'Half board', 'All-inclusive'].map((item) => <label key={item}><input type="checkbox" checked={selectedBoard === item} onChange={() => setSelectedBoard(selectedBoard === item ? null : item)} /> {item}</label>)}</div><div className="hotel-filter-group"><span>RATE POLICY</span><label><input type="checkbox" checked={instant} onChange={() => setInstant(!instant)} /> Instant confirmation</label><label><input type="checkbox" /> Free cancellation</label></div><button className="hotel-filter-reset" onClick={clearFilters}>Clear all filters</button></aside>
        <section className="hotel-results"><div className="hotel-results-toolbar"><div><strong>{results.length * 24}</strong> properties found in <strong>{query || 'all destinations'}</strong><small>09 Sep — 10 Sep 2026 · 1 room · 2 guests</small></div><div className="hotel-results-actions"><button onClick={() => setSort(sort === 'Recommended' ? 'Lowest price' : 'Recommended')}>Sort: {sort} <ChevronDown size={14} /></button><button className={compared.size ? 'active' : ''} onClick={() => notify(`Comparing ${compared.size} properties`)}><Eye size={14} /> Compare ({compared.size})</button></div></div>{results.length ? <div className="hotel-card-list">{results.map((hotel) => <article className="hotel-result-card" key={hotel.id} style={{ borderLeft: compared.has(hotel.id) ? '4px solid #DF251B' : '4px solid transparent' }}><div className="hotel-card-main"><div className={`hotel-thumb ${hotel.tone}`}><span>{hotel.name.slice(0, 1)}</span><small>PHOTO</small></div><div className="hotel-result-info"><div className="hotel-result-title"><div><h2>{hotel.name} <span className="hotel-stars">{'★'.repeat(hotel.stars)}</span></h2><p><MapPin size={12} /> {hotel.city} · {hotel.distance}</p><div className="hotel-rating"><b>{hotel.rating}/5</b> <span>Excellent ({hotel.reviews.toLocaleString()} reviews)</span></div></div><div className="hotel-actions"><button className={liked.has(hotel.id) ? 'liked' : ''} onClick={() => setLiked(toggleSet(liked, hotel.id))} aria-label={`Save ${hotel.name}`}><Heart size={15} fill={liked.has(hotel.id) ? '#DF251B' : 'none'} /></button><button className={compared.has(hotel.id) ? 'active' : ''} onClick={() => setCompared(toggleSet(compared, hotel.id))} aria-label={`Compare ${hotel.name}`}><Check size={15} /></button></div></div><div className="hotel-amenities">{hotel.amenities.map((amenity) => <span key={amenity}><Wifi size={11} /> {amenity}</span>)}</div><div className="hotel-supplier-line">{hotel.supplier} <span>·</span> {hotel.board} <span>·</span> Free cancellation available</div></div></div><div className="hotel-result-pricing"><span className="hotel-discount">35% off</span><small>1 night · 2 guests</small><strong>AED {hotel.price}</strong><small>+ taxes and fees</small><button className="hotel-search-button" onClick={() => { setSelected(hotel); notify('Room details opened') }}>Book this room <Search size={14} /></button></div></article>)}</div> : <div className="hotel-empty"><strong>No hotels match these filters</strong><span>Clear filters or search another destination.</span><button className="hotel-search-button" onClick={clearFilters}>Clear filters</button></div>}</section>
      </div>
    </main>
    {selected && <div className="hotel-modal-backdrop" onClick={() => setSelected(null)}><div className="hotel-modal" onClick={(e) => e.stopPropagation()}><button className="hotel-modal-close" onClick={() => setSelected(null)} aria-label="Close"><X size={17} /></button><span className="hotel-eyebrow">ROOMS & RATES · {selected.id}</span><h2>{selected.name}</h2><p><MapPin size={13} /> {selected.city}</p><div className="hotel-room"><div><strong>Deluxe King Room</strong><small>{selected.board} · Free cancellation until 07 Sep</small></div><b>AED {selected.price}<small>/ night</small></b></div><div className="hotel-room"><div><strong>Executive Suite</strong><small>Breakfast included · Sea view</small></div><b>AED {selected.price + 220}<small>/ night</small></b></div><button className="hotel-search-button full" onClick={() => { setSelected(null); notify('Room selected — booking flow opened') }}>Continue to booking <Search size={15} /></button></div></div>}
    {toast && <div className="hotel-toast">{toast}</div>}
  </div>
}
