-- Hotel images (ADR 0027). The image bytes live in PostgreSQL (bytea) behind a storage port, so no external storage account is
-- needed for the MVP; the port lets a later ADR move the bytes to object storage without changing the API.
--
-- Integrity beyond Prisma: JPEG, PNG or WebP only; 1 byte to 5 MiB and "bytes" equal to the stored length; pixel size 800x600 to
-- 8000x8000 (width and height both); alt text 1 to 200 characters; sha256 as 64 hex characters; sort order >= 0.
-- One image per hotel and content hash (duplicates are refused), and at most one primary image per hotel (partial unique index).
-- The 30-images-per-hotel limit is enforced by the API under a per-hotel advisory lock, not by the database.
-- "uploaded_by_id" is plain text without a foreign key so history survives user removal.
--
-- Tenant indexes: "tenant_id" leads the non-unique index. The list query never reads "data"; Prisma selects omit it.
--
-- The conditional GRANT mirrors earlier migrations (ADR 0013): it is a production privilege change in effect and needs the human
-- decision before this migration is applied to any persistent environment. Without it the API reports images as unavailable.
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP TABLE IF EXISTS "HotelImage";

-- CreateTable
CREATE TABLE "HotelImage" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "bytes" INTEGER NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "sha256" CHAR(64) NOT NULL,
    "alt_text" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_primary" BOOLEAN NOT NULL DEFAULT false,
    "data" BYTEA NOT NULL,
    "uploaded_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HotelImage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "HotelImage_hotel_id_sha256_key" ON "HotelImage"("hotel_id", "sha256");

-- CreateIndex
CREATE INDEX "HotelImage_tenant_id_hotel_id_sort_order_idx" ON "HotelImage"("tenant_id", "hotel_id", "sort_order");

-- One primary image per hotel
CREATE UNIQUE INDEX "HotelImage_one_primary_per_hotel" ON "HotelImage"("hotel_id") WHERE "is_primary";

-- AddForeignKey
ALTER TABLE "HotelImage" ADD CONSTRAINT "HotelImage_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HotelImage" ADD CONSTRAINT "HotelImage_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Integrity constraints
ALTER TABLE "HotelImage" ADD CONSTRAINT "HotelImage_content_type" CHECK ("content_type" IN ('image/jpeg', 'image/png', 'image/webp')),
  ADD CONSTRAINT "HotelImage_size" CHECK ("bytes" BETWEEN 1 AND 5242880 AND "bytes" = octet_length("data")),
  ADD CONSTRAINT "HotelImage_dimensions" CHECK ("width" BETWEEN 800 AND 8000 AND "height" BETWEEN 600 AND 8000),
  ADD CONSTRAINT "HotelImage_alt_text" CHECK (char_length("alt_text") BETWEEN 1 AND 200 AND "alt_text" = btrim("alt_text")),
  ADD CONSTRAINT "HotelImage_sha256_format" CHECK ("sha256" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "HotelImage_sort_order" CHECK ("sort_order" >= 0);

-- Row-level security: tenant isolation.
ALTER TABLE "HotelImage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HotelImage" FORCE ROW LEVEL SECURITY;
CREATE POLICY "HotelImage_tenant_isolation" ON "HotelImage" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "HotelImage" TO fbeds_api';
  END IF;
END $$;
