-- Hotel and room amenities (ADR 0021, stage 2). Selections from a controlled catalogue defined in @bedbanks/contracts; the database
-- stores only the code and whether it is free, paid or unknown. A missing row means "not recorded", never "absent".
--
-- "RoomAmenity" has a composite foreign key to "RoomType"("hotel_id","id"), so a room amenity cannot name a room of another hotel.
-- Codes are format-checked; the catalogue itself lives in application code so it can grow without a migration.
-- Nothing commercial: no rate, inventory, price or booking state.
--
-- Tenant indexes: tenant_id leads each non-unique index; uniqueness is per hotel (or room) and code.
--
-- The conditional GRANTs mirror earlier migrations (ADR 0013) and need the human decision before any persistent environment.
-- Without them the API reports amenities as unavailable and never as empty.
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP TABLE IF EXISTS "RoomAmenity", "HotelAmenity"; DROP TYPE IF EXISTS "AmenityFeeType";

-- CreateEnum
CREATE TYPE "AmenityFeeType" AS ENUM ('FREE', 'PAID', 'UNKNOWN');

-- CreateTable
CREATE TABLE "HotelAmenity" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "fee_type" "AmenityFeeType" NOT NULL DEFAULT 'UNKNOWN',
    "updated_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HotelAmenity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoomAmenity" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "room_type_id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "fee_type" "AmenityFeeType" NOT NULL DEFAULT 'UNKNOWN',
    "updated_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RoomAmenity_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "HotelAmenity_hotel_id_code_key" ON "HotelAmenity"("hotel_id", "code");

-- CreateIndex
CREATE INDEX "HotelAmenity_tenant_id_hotel_id_idx" ON "HotelAmenity"("tenant_id", "hotel_id");

-- CreateIndex
CREATE UNIQUE INDEX "RoomAmenity_room_type_id_code_key" ON "RoomAmenity"("room_type_id", "code");

-- CreateIndex
CREATE INDEX "RoomAmenity_tenant_id_hotel_id_idx" ON "RoomAmenity"("tenant_id", "hotel_id");

-- AddForeignKey
ALTER TABLE "HotelAmenity" ADD CONSTRAINT "HotelAmenity_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HotelAmenity" ADD CONSTRAINT "HotelAmenity_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoomAmenity" ADD CONSTRAINT "RoomAmenity_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoomAmenity" ADD CONSTRAINT "RoomAmenity_hotel_id_room_type_id_fkey" FOREIGN KEY ("hotel_id", "room_type_id") REFERENCES "RoomType"("hotel_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Integrity constraints
ALTER TABLE "HotelAmenity" ADD CONSTRAINT "HotelAmenity_code_format" CHECK ("code" ~ '^[A-Z][A-Z0-9_]{1,39}$');
ALTER TABLE "RoomAmenity" ADD CONSTRAINT "RoomAmenity_code_format" CHECK ("code" ~ '^[A-Z][A-Z0-9_]{1,39}$');

-- Row-level security: tenant isolation on both tables.
ALTER TABLE "HotelAmenity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HotelAmenity" FORCE ROW LEVEL SECURITY;
CREATE POLICY "HotelAmenity_tenant_isolation" ON "HotelAmenity" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "RoomAmenity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoomAmenity" FORCE ROW LEVEL SECURITY;
CREATE POLICY "RoomAmenity_tenant_isolation" ON "RoomAmenity" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "HotelAmenity" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "RoomAmenity" TO fbeds_api';
  END IF;
END $$;
