'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { PageHeader } from '@/components/common/PageHeader'
import { StatusBadge } from '@/components/status/StatusBadge'
import { AdminLoadingState, AdminServiceUnavailable, AccessDenied, AuthRequired } from '@/components/auth/AuthorizationStates'
import { apiRequest } from '@/lib/api/client'
import { ApiResponseError } from '@/lib/api/errors'

type Room={id:string;hotelId:string;name:string;code:string;maxAdults:number;maxChildren:number;maxOccupancy:number;beddingMetadata:Record<string,unknown>;isActive:boolean;updatedAt:string}
export default function RoomDetailPage(){
 const {id,roomId}=useParams<{id:string;roomId:string}>();const [room,setRoom]=useState<Room|null>(null);const [state,setState]=useState<'loading'|'ready'|'error'|'auth'|'forbidden'>('loading');const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',code:'',maxAdults:'2',maxChildren:'0',maxOccupancy:'2',bedding:'',isActive:true})
 useEffect(()=>{let active=true;apiRequest<Room>(`/supply/hotels/${id}/rooms/${roomId}`).then(v=>{if(active){setRoom(v);setForm({name:v.name,code:v.code,maxAdults:String(v.maxAdults),maxChildren:String(v.maxChildren),maxOccupancy:String(v.maxOccupancy),bedding:typeof v.beddingMetadata?.description==='string'?String(v.beddingMetadata.description):'',isActive:v.isActive});setState('ready')}}).catch(e=>{if(!active)return;if(e instanceof ApiResponseError&&e.status===401)setState('auth');else if(e instanceof ApiResponseError&&[403,404].includes(e.status))setState('forbidden');else setState('error')});return()=>{active=false}},[id,roomId])
 async function save(){setSaving(true);try{const v=await apiRequest<Room>(`/supply/hotels/${id}/rooms/${roomId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,code:form.code,maxAdults:Number(form.maxAdults),maxChildren:Number(form.maxChildren),maxOccupancy:Number(form.maxOccupancy),beddingMetadata:form.bedding?{description:form.bedding}:{},isActive:form.isActive})});setRoom(v)}finally{setSaving(false)}}
 if(state==='loading')return <div className="admin-page"><AdminLoadingState /></div>;if(state==='auth')return <div className="admin-page"><AuthRequired /></div>;if(state==='forbidden')return <div className="admin-page"><AccessDenied permission="supply.rooms.read" /></div>;if(state==='error')return <div className="admin-page"><AdminServiceUnavailable onRetry={()=>window.location.reload()} /></div>
 return <div className="admin-page">{room&&<><PageHeader eyebrow={`ROOM · ${room.id}`} title={room.name} description={`${room.code} · max occupancy ${room.maxOccupancy}`} actions={<StatusBadge status={room.isActive?'active':'inactive'} />} /><div className="workspace-panel" style={{display:'grid',gap:14,padding:22,maxWidth:720}}><label>ROOM NAME<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="input-wrap" /></label><label>ROOM CODE<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="input-wrap" /></label><label>MAX ADULTS<input type="number" min="1" value={form.maxAdults} onChange={e=>setForm({...form,maxAdults:e.target.value})} className="input-wrap" /></label><label>MAX CHILDREN<input type="number" min="0" value={form.maxChildren} onChange={e=>setForm({...form,maxChildren:e.target.value})} className="input-wrap" /></label><label>MAX OCCUPANCY<input type="number" min="1" value={form.maxOccupancy} onChange={e=>setForm({...form,maxOccupancy:e.target.value})} className="input-wrap" /></label><label>BEDDING<input value={form.bedding} onChange={e=>setForm({...form,bedding:e.target.value})} className="input-wrap" /></label><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})} /> Active</label><button type="button" className="button primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save changes'}</button></div></>}</div>
}
