// Real-stack browser verification of the hotel commercial workspace. See README.md. Not run in CI.
const path = require('path')
const { createRequire } = require('module')
const req = createRequire(path.join(__dirname, '../../apps/website/package.json'))
const { chromium } = req('@playwright/test')
const AxeBuilder = req('@axe-core/playwright').default || req('@axe-core/playwright')
const seed = require(process.env.SEED_JSON ?? path.join(__dirname, '.seed-hotels.json'))
const BASE = process.env.ADMIN_URL ?? 'http://localhost:3000'
const SHOTS = process.env.SHOT_DIR ?? require('os').tmpdir()
const H = seed.hotels
const results = []
const check = (name, ok, extra = '') => { results.push({ name, ok: !!ok }); console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${extra ? '  — ' + String(extra).slice(0, 160) : ''}`) }
const text = async (page) => (await page.locator('main, .admin-page').first().innerText()).replace(/\s+/g, ' ')
const stateOf = async (page) => page.locator('[data-state]').first().getAttribute('data-state')
const rows = (page) => page.locator('[data-testid=hotels-table] tbody tr').count()

async function login(browser, email, viewport) {
  const ctx = await browser.newContext(viewport ? { viewport } : {}); const page = await ctx.newPage()
  await page.goto(`${BASE}/login`); await page.fill('#email', email); await page.fill('#password', seed.password)
  await page.click('button[type=submit]'); await page.waitForURL((u) => !u.pathname.startsWith('/login'), { timeout: 20000 })
  return { ctx, page }
}
async function openHotel(page, key, tab) {
  await page.goto(`${BASE}/hotels/${H[key]}${tab ? `?tab=${tab}` : ''}`)
  await page.waitForSelector('[data-testid=hotel-header], [data-state]', { timeout: 20000 })
}

;(async () => {
  const browser = await chromium.launch()
  const { ctx, page } = await login(browser, seed.ownerEmail)
  const errors = []; page.on('pageerror', (e) => errors.push(e.message))

  // ---- list: summary, server pagination, search, filters, shareable URLs -------------------------------------------------
  await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-testid=hotels-table]', { timeout: 20000 }); await page.waitForSelector('[data-testid=hotels-summary]')
  const summary = (await page.locator('[data-testid=hotels-summary]').innerText()).replace(/\s+/g, ' ')
  check('summary shows tenant-wide total (34) from the API', /34 Total hotels/.test(summary), summary.slice(0, 120))
  check('page 1 shows 25 rows', (await rows(page)) === 25)
  // dashboard sellability card shows the same API counts as the list summary, and a failure is not shown as zero
  const tile = (label) => Number((summary.match(new RegExp(`(\\d+) ${label}`)) ?? [])[1])
  await page.goto(`${BASE}/dashboard`); await page.waitForSelector('[data-testid=dashboard-sellability] [aria-label*=ready]', { timeout: 20000 })
  const card = (await page.locator('[data-testid=dashboard-sellability]').innerText()).replace(/\s+/g, ' ')
  const cardLabel = await page.locator('[data-testid=dashboard-sellability] [role=img]').getAttribute('aria-label')
  check('dashboard sellability card matches the hotel list summary', cardLabel === `${tile('Ready')} ready, ${tile('Partial')} partial, ${tile('Blocked')} blocked of 34 hotels`, cardLabel)
  check('dashboard card links to filtered hotels and exceptions', (await page.locator('[data-testid=dashboard-sellability] a[href*="readiness=BLOCKED"]').count()) === 1 && /View exceptions/.test(card))
  await page.route('**/api/v1/admin/operations/hotels/summary*', (r) => r.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, error: { code: 'OPERATIONS_READ_DENIED', message: 'denied' } }) }))
  await page.reload(); await page.waitForSelector('[data-testid=dashboard-sellability] [data-state]', { timeout: 20000 })
  check('a failed summary shows an explicit state on the card, not zero hotels', (await page.locator('[data-testid=dashboard-sellability] [data-state=denied]').count()) === 1 && !/0 ready/.test(await page.locator('[data-testid=dashboard-sellability]').innerText()))
  await page.unroute('**/api/v1/admin/operations/hotels/summary*')
  await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-testid=hotels-table]'); await page.waitForSelector('[data-testid=hotels-summary]')
  check('pager reports total and page', /34 results · page 1 of 2/.test(await page.locator('[data-testid=pager]').innerText()))
  await page.getByRole('button', { name: 'Next page' }).click(); await page.waitForFunction(() => location.search.includes('page=2'))
  await page.waitForSelector('[data-testid=hotels-table] tbody tr'); await page.waitForTimeout(400)
  check('page 2 (final) shows the remaining 9 rows and the URL carries the page', (await rows(page)) === 9 && page.url().includes('page=2'))
  await page.screenshot({ path: `${SHOTS}/hotels-list.png`, fullPage: true })
  await page.goto(`${BASE}/hotels?search=Atlantis`); await page.waitForSelector('[data-testid=hotels-table]')
  check('search by name (server-side, shareable URL)', (await rows(page)) === 1 && /Atlantis Palm Resort/.test(await text(page)))
  await page.goto(`${BASE}/hotels?search=${encodeURIComponent('ALPHA-' + seed.tag.slice(-4))}`); await page.waitForSelector('[data-testid=hotels-table]')
  check('search by hotel code', (await rows(page)) === 1)
  await page.goto(`${BASE}/hotels?search=%25`); await page.waitForSelector('[data-state=empty], [data-testid=hotels-table]')
  check('a "%" search is literal and matches nothing', (await stateOf(page)) === 'empty')
  await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-testid=hotels-table]')
  await page.getByLabel('Destination').selectOption('Abu Dhabi'); await page.waitForFunction(() => location.search.includes('destination'))
  await page.waitForTimeout(500)
  check('destination filter', (await rows(page)) === 1 && /Corniche Abu Dhabi Hotel/.test(await text(page)))
  for (const [qs, label, expectName, expectCount] of [['readiness=BLOCKED', 'readiness=BLOCKED', 'Deira Gate Hotel', null], ['readiness=PARTIAL', 'readiness=PARTIAL', 'Burj View Hotel', null], ['mapping=NONE', 'mapping=NONE', 'Karama Budget Stay', 1], ['contractState=EXPIRING', 'contract EXPIRING', 'Jumeirah Beach Club', 1], ['contractState=EXPIRED', 'contract EXPIRED', 'Emirates Old Town', 1], ['expiresWithinDays=30', 'expires within 30d', 'Jumeirah Beach Club', 1], ['issue=STOP_SELL', 'issue=STOP_SELL', 'Hatta Mountain Lodge', null], ['issue=RATE_MISSING', 'issue=RATE_MISSING', 'Festival City Suites', 1], ['issue=AVAILABILITY_MISSING', 'issue=AVAILABILITY_MISSING', 'Gold Souk Residence', 1], ['issue=NO_INVENTORY', 'issue=NO_INVENTORY', 'Marina Bay Towers', 1], ['mapping=PENDING', 'mapping=PENDING', 'Creek Harbour Inn', 1]]) {
    await page.goto(`${BASE}/hotels?${qs}`); await page.waitForSelector('[data-testid=hotels-table], [data-state]')
    const body = await text(page); const n = await rows(page)
    check(`filter ${label} (server-side)`, body.includes(expectName) && (expectCount === null || n === expectCount), `${n} rows`)
  }
  await page.goto(`${BASE}/hotels?readiness=BLOCKED`); await page.waitForSelector('[data-testid=hotels-table]')
  const chips = await page.locator('[data-testid=hotels-table] tbody tr td:nth-child(11)').allInnerTexts()
  check('every row of the BLOCKED filter shows a BLOCKED chip', chips.length > 0 && chips.every((c) => /BLOCKED/.test(c)), chips.join(','))
  await page.goto(`${BASE}/hotels?search=zzzzzzzz`); await page.waitForSelector('[data-state=empty]')
  check('no match is the EMPTY state with a successful message, not an error', /No hotels match these filters/.test(await text(page)) && (await page.locator('[role=alert]:not(#__next-route-announcer__)').count()) === 0)

  // ---- failure states are distinct and never an empty list -----------------------------------------------------------------
  for (const [status, code, expect, label] of [[401, 'UNAUTHORIZED', 'unauthenticated', '401'], [403, 'FORBIDDEN', 'forbidden', '403'], [503, 'OPERATIONS_READ_DENIED', 'denied', '503 denied'], [500, 'INTERNAL_SERVER_ERROR', 'error', '500']]) {
    await page.route('**/api/v1/admin/operations/hotels?*', (r) => r.fulfill({ status, contentType: 'application/json', headers: { 'x-request-id': 'req-hotels-1' }, body: JSON.stringify({ success: false, error: { code, message: 'x', details: [] }, meta: {} }) }))
    await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-state]', { timeout: 15000 })
    const state = await stateOf(page); const body = await text(page)
    check(`list API ${label} renders "${expect}" and never "No hotels"`, state === expect && !/No hotels/.test(body) && /req-hotels-1|HTTP/.test(body), `${state}`)
    await page.unroute('**/api/v1/admin/operations/hotels?*')
  }
  await page.route('**/api/v1/admin/operations/hotels?*', (r) => r.abort()); await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-state]', { timeout: 15000 })
  check('network failure renders "unreachable"', (await stateOf(page)) === 'unreachable'); await page.unroute('**/api/v1/admin/operations/hotels?*')
  await page.route('**/api/v1/admin/operations/hotels/summary*', (r) => r.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ success: false, error: { code: 'OPERATIONS_READ_DENIED', message: 'x', details: [] }, meta: {} }) }))
  await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-testid=hotels-table]')
  check('a failed summary does not hide the list, and says it is unavailable', (await page.locator('[data-testid=summary-unavailable]').count()) === 1 && (await rows(page)) === 25); await page.unroute('**/api/v1/admin/operations/hotels/summary*')

  // ---- Hotel 360 -------------------------------------------------------------------------------------------------------------
  await openHotel(page, 'alpha')
  let header = (await page.locator('[data-testid=hotel-header]').innerText()).replace(/\s+/g, ' ')
  check('READY hotel: header shows READY, Sellable to Agents YES, supplier, code and canonical id', /READY/.test(header) && /Sellable to Agents\s*YES/.test(header) && /Gulf Direct/.test(header) && header.includes(H.alpha) && /ALPHA-/.test(header), header.slice(0, 140))
  const gates = await page.locator('[data-testid=readiness-gates] li').evaluateAll((els) => els.map((e) => e.getAttribute('data-state')))
  check('READY hotel: all 12 readiness gates PASS', gates.length === 12 && gates.every((g) => g === 'PASS'), gates.join(','))
  check('READY hotel: no commercial issues', (await page.locator('[data-testid=issues-empty]').count()) === 1)
  await page.screenshot({ path: `${SHOTS}/hotel-360-overview.png`, fullPage: true })

  await openHotel(page, 'bravo')
  header = (await page.locator('[data-testid=hotel-header]').innerText()).replace(/\s+/g, ' ')
  check('PARTIAL hotel: header shows PARTIAL and issues list names STOP_SELL', /PARTIAL/.test(header) && (await page.locator('[data-testid=issue-list] [data-category=STOP_SELL]').count()) === 1)
  await page.locator('[data-testid=issue-list] [data-category=STOP_SELL] a').first().click(); await page.waitForURL(/tab=rates/); await page.waitForSelector('[data-testid=calendar]')
  check('an issue links to the section that resolves it, at the affected night and room (Rates & Inventory)', /tab=rates/.test(page.url()) && /from=\d{4}-\d{2}-\d{2}/.test(page.url()) && /roomTypeId=/.test(page.url()), page.url().slice(-110))
  const stopCell = page.locator('[data-testid=calendar] tr[data-sellable=false]').first()
  check('calendar marks the stop-sold night NOT SELLABLE with the canonical reason', (await stopCell.count()) === 1 && /STOP_SELL/.test(await stopCell.innerText()) && /STOP SELL/.test(await stopCell.innerText()))
  const calText = await page.locator('[data-testid=calendar]').innerText()
  check('calendar shows integer-minor rates as currency (AED 499.00) and remaining inventory', /AED\s?499\.00/.test(calText) && /\b6\b/.test(calText), calText.slice(0, 120))
  check('the calendar links into the existing rates workbench for the plan (read-only here, edited where validation and audit live)', (await page.locator('a[href^="/rates?ratePlanId="]').count()) >= 1)
  await page.screenshot({ path: `${SHOTS}/hotel-360-calendar.png`, fullPage: true })

  await openHotel(page, 'charlie')
  check('mapping-pending hotel: CRITICAL UNMAPPED_HOTEL issue with canonical reason', (await page.locator('[data-testid=issue-list] [data-category=UNMAPPED_HOTEL][data-severity=CRITICAL]').count()) >= 1)
  await page.locator('[data-testid=issue-list] [data-category=UNMAPPED_HOTEL] a').first().click(); await page.waitForURL(/tab=mappings/); await page.waitForSelector('table, [data-testid=hotel-mapping-empty]')
  check('mapping tab shows the PENDING supplier mapping and the unmapped rooms (never inferred)', /PENDING/.test(await text(page)) && (await page.locator('[data-testid=unmapped-rooms] li').count()) === 2)

  await openHotel(page, 'delta', 'rooms'); await page.waitForSelector('[data-room-id]')
  check('room-mapping failure: rooms tab shows NOT MAPPED and BLOCKED with the canonical blocker', /NOT MAPPED/.test(await text(page)) && /SUPPLIER_MAPPING_INVALID/.test(await text(page)))
  await openHotel(page, 'echo', 'contracts'); await page.waitForSelector('[data-testid=sellability-chain]'); await page.waitForSelector('table')
  check('expired contract: contracts tab shows EXPIRED and a failed contract step in the chain', /EXPIRED/.test(await text(page)) && /Contract active\s*FAIL/.test(await page.locator('[data-testid=sellability-chain]').innerText().then((t) => t.replace(/\s+/g, ' '))))
  await openHotel(page, 'juliet', 'contracts'); await page.waitForSelector('table')
  check('expiring contract: shows EXPIRING and the days left', /EXPIRING/.test(await text(page)) && /21d|20d/.test(await text(page)))
  await openHotel(page, 'juliet')
  check('expiring contract appears as a WARNING issue', (await page.locator('[data-testid=issue-list] [data-category=CONTRACT_EXPIRING][data-severity=WARNING]').count()) === 1)
  await openHotel(page, 'kilo')
  check('brand-new hotel is BLOCKED with critical issues, never "ready"', /BLOCKED/.test(await page.locator('[data-testid=hotel-header]').innerText()) && (await page.locator('[data-testid=issue-list] [data-severity=CRITICAL]').count()) >= 2)

  // ---- sellability inspector --------------------------------------------------------------------------------------------------
  await openHotel(page, 'alpha', 'sellability')
  await page.getByRole('button', { name: 'Check sellability' }).click(); await page.waitForSelector('[data-testid=sellability-result]')
  let res = (await page.locator('[data-testid=sellability-result]').innerText()).replace(/\s+/g, ' ')
  check('supply-eligible stay: offers and the cheapest integer total (AED 1,497.00)', /SUPPLY ELIGIBLE/.test(res) && !/NOT ELIGIBLE/.test(res.slice(0, 20)) && /Offers:\s*2/.test(res) && /AED\s?1,497\.00/.test(res), res.slice(0, 160))
  check('a buyer-independent diagnostic never certifies buyer or Agent recheck', (await page.locator('[data-readiness-gate=distribution][data-state=UNKNOWN]').count()) === 2 && (await page.locator('[data-readiness-gate=search_recheck][data-state=UNKNOWN]').count()) === 2)
  await page.screenshot({ path: `${SHOTS}/sellability-ok.png`, fullPage: true })
  await openHotel(page, 'bravo', 'sellability')
  // the seeded stop-sell is on the 15th day from today for the Deluxe plan; stay nights d+14..d+16
  const day = (n) => new Date(Date.now() + n * 86_400_000).toISOString().slice(0, 10)
  await page.getByLabel('Check-in').fill(day(14)); await page.getByLabel('Check-out').fill(day(17))
  await page.getByRole('button', { name: 'Check sellability' }).click(); await page.waitForSelector('[data-testid=sellability-result]')
  const bad = page.locator('[data-testid=sellability-result] section[data-sellable=false]').first()
  const badText = (await bad.innerText()).replace(/\s+/g, ' ')
  check('multi-night failure: the Deluxe plan is NOT SELLABLE, names STOP_SELL and the failing night', (await bad.count()) === 1 && /STOP_SELL/.test(badText) && (await bad.locator(`li[data-date="${day(15)}"][data-sellable=false]`).count()) === 1 && (await bad.locator(`li[data-date="${day(14)}"][data-sellable=true]`).count()) === 1, badText.slice(0, 140))
  check('failed gate list shows Stop sell FAIL and Daily rate PASS', (await bad.locator('li[data-gate=stopSell][data-state=FAIL]').count()) === 1 && (await bad.locator('li[data-gate=rate][data-state=PASS]').count()) === 1)
  check('the other room stays sellable for the same dates (per-plan verdicts)', (await page.locator('[data-testid=sellability-result] section[data-sellable=true]').count()) === 1)
  await page.getByLabel('Check-out').fill(day(14)); check('editing stay criteria clears the old verdict before submitting', (await page.locator('[data-testid=sellability-result]').count()) === 0); await page.getByRole('button', { name: 'Check sellability' }).click(); await page.waitForSelector('[data-state]')
  check('an invalid stay shows the API validation message, not a result', /1-31 nights/.test(await text(page)) && (await page.locator('[data-testid=sellability-result]').count()) === 0)
  await page.screenshot({ path: `${SHOTS}/sellability-failed.png`, fullPage: true })
  let posts = 0; page.on('request', (r) => { if (r.url().includes('/sellability')) posts++ })
  await page.getByLabel('Check-out').fill(day(16)); await page.evaluate(() => { const b = [...document.querySelectorAll('button')].find((x) => /Check sellability/.test(x.textContent)); b.click(); b.click() })
  await page.waitForSelector('[data-testid=sellability-result]'); check('a double click sends one inspection request', posts === 1, `requests=${posts}`)

  // ---- bookings, holds, audit cross-navigation ----------------------------------------------------------------------------------
  await openHotel(page, 'alpha', 'bookings'); await page.waitForSelector('table')
  check('bookings tab lists the hotel booking with a link into Booking 360', (await page.locator('a[href^="/bookings/"]').count()) >= 1 && /BK1/.test(await text(page)))
  await page.getByRole('link', { name: 'All bookings for this hotel' }).click(); await page.waitForURL(/\/bookings\?hotelId=/); await page.waitForSelector('table')
  check('"All bookings" opens the booking list already filtered by this hotel (server-side)', /1 result/.test(await text(page)) && (await page.getByLabel('Hotel id').inputValue()) === H.alpha)
  await openHotel(page, 'alpha', 'audit'); await page.waitForSelector('table')
  check('audit tab shows the event with action and request id', /supply\.hotel\.updated/.test(await text(page)) && /req-verify-1/.test(await text(page)))

  // ---- exceptions ---------------------------------------------------------------------------------------------------------------
  await page.goto(`${BASE}/exceptions`); await page.waitForSelector('[data-testid=exceptions-table]')
  const counts = await page.locator('[data-testid=exception-counts]').innerText()
  check('exceptions centre lists issues with severity counts', /\d+ critical · \d+ high · \d+ warning/.test(counts) && (await page.locator('[data-testid=exceptions-table] tbody tr').count()) > 5, counts)
  const firstSeverity = await page.locator('[data-testid=exceptions-table] tbody tr').first().getAttribute('data-severity')
  check('exceptions are ordered most severe first', firstSeverity === 'CRITICAL')
  await page.getByLabel('Severity').selectOption('WARNING'); await page.waitForTimeout(600); await page.waitForSelector('[data-testid=exceptions-table]')
  const sev = await page.locator('[data-testid=exceptions-table] tbody tr').evaluateAll((els) => els.map((e) => e.getAttribute('data-severity')))
  check('severity filter applies on the server', sev.length > 0 && sev.every((s) => s === 'WARNING'), sev.join(','))
  await page.getByLabel('Severity').selectOption(''); await page.getByLabel('Category').selectOption('RATE_MISSING'); await page.waitForTimeout(600)
  await page.locator('[data-testid=exceptions-table] tbody tr a', { hasText: 'Resolve in' }).first().click(); await page.waitForURL(/\/hotels\/.+\?tab=rates/)
  check('an exception links to the exact hotel section to resolve it', /tab=rates/.test(page.url()))
  await page.screenshot({ path: `${SHOTS}/exceptions.png`, fullPage: true })

  // ---- Hotel Setup (ADR 0021): validation keeps input, stale edits fail, a draft saves incomplete and persists, publication is gated ----
  await openHotel(page, 'kilo')
  check('before: the unrated DRAFT hotel lists the star-rating and content issues', /no 1-5 star rating/i.test(await text(page)) && /content is not COMPLETE/i.test(await text(page)))
  await page.waitForSelector('[data-testid=profile-completeness]', { timeout: 15000 })
  check('the Overview shows an explicit completeness figure and names what is missing', /of 12 publication requirements met/.test(await text(page)) && (await page.locator('[data-testid=profile-completeness] [data-met=false]').count()) > 0)
  check('the Overview no longer carries a master-data form or placeholder summary', (await page.getByRole('button', { name: 'Save changes' }).count()) === 0 && !/mock summary/i.test(await text(page)))
  await page.getByRole('tab', { name: 'Hotel Setup' }).click(); await page.waitForSelector('[data-testid=setup-form]')
  check('Hotel Setup shows the immutable canonical id', (await page.locator('[data-testid=canonical-id]').innerText()).trim() === H.kilo)
  // a failed save keeps what was typed and says why
  await page.getByLabel('Latitude').fill('95'); await page.getByLabel('Longitude').fill('55.2'); await page.getByLabel('Area').fill('Business Bay')
  await page.getByTestId('setup-save').click(); await page.waitForSelector('[data-testid=setup-error]')
  const badNotice = await page.getByTestId('setup-error').innerText()
  check('a validation failure names the field and keeps the typed values', /latitude/i.test(badNotice) && (await page.getByLabel('Latitude').inputValue()) === '95' && (await page.getByLabel('Area').inputValue()) === 'Business Bay')
  // a stale edit from a second window fails visibly
  const { ctx: c2, page: p2 } = await login(browser, seed.ownerEmail)
  await p2.goto(`${BASE}/hotels/${H.kilo}?tab=setup`); await p2.waitForSelector('[data-testid=setup-form]')
  await page.getByLabel('Latitude').fill('25.1'); await page.getByLabel('Longitude').fill('55.2')
  await page.getByLabel('Street address').fill('1 Verification Road'); await page.getByLabel('Star category').selectOption('4'); await page.getByLabel('Category verified').check()
  await page.getByLabel('Source of the category').fill('Verification register')
  await page.getByLabel('Short description (max 500)').fill('A verification hotel in Business Bay.')
  await page.getByLabel('Check-in time (hotel local)').fill('14:00'); await page.getByLabel('Check-out time (hotel local)').fill('12:00')
  await page.getByLabel('reservations name').fill('Front desk'); await page.getByLabel('reservations email').fill('verify-res@hotel.test')
  await page.getByRole('button', { name: 'Add identifier' }).click(); await page.locator('[data-testid=external-identifiers] input').nth(1).fill(`GV-${Date.now()}`)
  await page.getByTestId('setup-save').click(); await page.waitForSelector('[data-testid=setup-notice]:has-text("Saved")', { timeout: 15000 })
  const saveRequestId = await page.getByTestId('setup-request-id').innerText()
  check('a save shows the persisted result and the server request id', saveRequestId.length > 8)
  await p2.getByLabel('Area').fill('Somewhere else'); await p2.getByTestId('setup-save').click(); await p2.waitForSelector('[data-testid=setup-error]')
  check('a stale edit fails visibly and offers to load the latest version', /changed after you loaded/i.test(await p2.getByTestId('setup-error').innerText()) && (await p2.getByRole('button', { name: /Load the latest version/ }).count()) === 1)
  await c2.close()
  await page.reload(); await page.waitForSelector('[data-testid=setup-form]')
  check('after a reload the saved draft is read back from the server', (await page.getByLabel('Street address').inputValue()) === '1 Verification Road' && (await page.getByLabel('Area').inputValue()) === 'Business Bay' && (await page.getByLabel('Star category').inputValue()) === '4')
  check('the audit trail records the same server request id', await (async () => { await page.goto(`${BASE}/hotels/${H.kilo}?tab=audit`); await page.waitForSelector('table[aria-label="Hotel audit events"]'); return (await text(page)).includes(saveRequestId) && /hotel\.setup\.updated/.test(await text(page)) })())
  // publication is gated, then allowed once the requirements are met
  await page.goto(`${BASE}/hotels/${H.kilo}?tab=setup`); await page.waitForSelector('[data-testid=status-form]')
  check('the status form states that publication enables no booking or payment path', /does not enable booking, payment or supplier access/.test(await page.getByTestId('status-form').innerText()))
  check('the status form no longer offers COMPLETE: publication needs a second approver', !(await page.getByTestId('status-form').locator('option', { hasText: /^COMPLETE$/ }).count()))
  await page.getByTestId('publication').getByLabel('Reason (required)').fill('Reviewed against the verification register'); await page.getByTestId('publication-request').click()
  await page.waitForSelector('[data-testid=publication-state]:has-text("PENDING")', { timeout: 15000 })
  check('the requester can withdraw but cannot approve their own request', (await page.getByTestId('publication-cancel').count()) === 1 && (await page.getByTestId('publication-approve').count()) === 0)
  const { ctx: cc, page: cp } = await login(browser, seed.checkerEmail)
  await cp.goto(`${BASE}/hotels/${H.kilo}?tab=setup`); await cp.waitForSelector('[data-testid=publication-approve]', { timeout: 20000 })
  check('a different manager sees approve and reject, and no way to publish yet', (await cp.getByTestId('publication-reject').count()) === 1 && (await cp.getByTestId('publication-execute').count()) === 0)
  await cp.getByTestId('publication').getByLabel('Decision reason (required)').fill('Checked against the register'); await cp.getByTestId('publication-approve').click()
  await cp.waitForSelector('[data-testid=publication-execute]', { timeout: 15000 }); await cc.close()
  await page.reload(); await page.waitForSelector('[data-testid=publication-execute]', { timeout: 20000 })
  await page.getByTestId('publication-execute').click()
  await page.waitForSelector('[data-testid=profile-status]:has-text("COMPLETE")', { timeout: 15000 }); await page.waitForTimeout(800)
  check('after approval by another manager the profile is published, and the status persists', (await page.getByTestId('profile-status').innerText()).trim() === 'COMPLETE')
  await openHotel(page, 'kilo')
  const after = await text(page)
  check('after saving, the star-rating and content issues are gone, and the hotel is still BLOCKED by what is genuinely missing', !/no 1-5 star rating/i.test(after.replace(/Agents cannot list this hotel until one is set\./, '')) && !/content is not COMPLETE/i.test(after) && /BLOCKED/.test(await page.locator('[data-testid=hotel-header]').innerText()) && /No rate plan is configured/.test(after), after.slice(0, 80))

  // ---- Add Hotel never implies "ready": a hotel created through the real form is BLOCKED until downstream authority exists -------------
  await page.goto(`${BASE}/hotels/new`); await page.waitForSelector('form')
  await page.getByLabel(/^name$/i).fill('Brand New Verification Hotel'); await page.getByLabel(/^city$/i).fill('Dubai'); await page.getByLabel(/^country code$/i).fill('AE'); await page.getByLabel(/^external ref$/i).fill('NEW-VERIFY-1')
  await page.getByRole('button', { name: 'Create hotel' }).click(); await page.waitForURL(/\/hotels\/[^/?]+\?tab=setup$/, { timeout: 20000 }); await page.waitForSelector('[data-testid=setup-form]')
  check('Add hotel hands off to the Hotel Setup tab', /tab=setup/.test(page.url()))
  await page.goto(page.url().replace(/\?tab=setup$/, '')); await page.waitForSelector('[data-testid=hotel-header]')
  const created = (await page.locator('[data-testid=hotel-header]').innerText()).replace(/\s+/g, ' ')
  check('a newly created hotel opens as BLOCKED, "Sellable to Agents NO", status DRAFT', /BLOCKED/.test(created) && /Sellable to Agents\s*NO/.test(created) && /DRAFT/.test(created), created.slice(0, 120))
  check('a newly created hotel lists RATE_PLAN_MISSING and an unmapped-hotel issue as critical', (await page.locator('[data-testid=issue-list] [data-severity=CRITICAL]').count()) >= 2 && /No rate plan is configured/.test(await text(page)))

  // ---- Rooms, amenities, policies and images (ADR 0021, stage 2) ----
  await openHotel(page, 'kilo', 'rooms'); await page.waitForSelector('[data-testid=hotels-rooms], table[aria-label=Rooms]')
  const roomsBefore = await page.locator('table[aria-label=Rooms] tbody tr').count()
  await page.getByRole('button', { name: '+ Add room' }).click(); await page.waitForSelector('[data-testid=room-editor]')
  await page.getByLabel('Room name').fill('Verification Suite'); await page.getByLabel('Room code').fill('VS-1')
  await page.getByLabel('Max adults').fill('2'); await page.getByLabel('Max children').fill('3'); await page.getByLabel('Max total occupancy').fill('3')
  await page.getByTestId('room-save').click(); await page.waitForSelector('[data-testid=room-error]')
  check('a room that breaks the occupancy rule is refused with the rule named, and the typed values stay', /maxOccupancy: must be at least/.test(await page.getByTestId('room-error').innerText()) && (await page.getByLabel('Room name').inputValue()) === 'Verification Suite' && (await page.getByLabel('Max children').inputValue()) === '3')
  await page.getByLabel('Max total occupancy').fill('5'); await page.getByLabel('King beds').fill('1'); await page.getByLabel('Extra bed').selectOption('SUPPORTED'); await page.getByLabel('Balcony', { exact: true }).check()
  await page.getByTestId('room-save').click(); await page.waitForSelector('[data-testid=rooms-flash]:has-text("Room created")', { timeout: 15000 })
  await page.waitForFunction((n) => document.querySelectorAll('table[aria-label=Rooms] tbody tr').length === n + 1, roomsBefore, { timeout: 15000 })
  check('a valid room is created once and listed with its bedding and amenity', /1 King/.test(await page.locator('tr', { hasText: 'Verification Suite' }).innerText()) && /Balcony/.test(await page.locator('tr', { hasText: 'Verification Suite' }).innerText()) && /Extra bed: supported/.test(await page.locator('tr', { hasText: 'Verification Suite' }).innerText()))
  await page.reload(); await page.waitForSelector('table[aria-label=Rooms]')
  check('after a reload the room and its bedding are read back from the server', (await page.locator('table[aria-label=Rooms] tbody tr').count()) === roomsBefore + 1 && /Verification Suite/.test(await text(page)))
  const suiteRow = () => page.locator('table[aria-label=Rooms] tbody tr', { hasText: 'Verification Suite' })
  await suiteRow().getByRole('button', { name: 'Edit' }).click(); await page.waitForSelector('[data-testid=room-editor]')
  await page.getByTestId('room-archive').click(); await page.waitForSelector('[data-testid=archive-confirm]')
  check('archiving explains that nothing is deleted and needs a reason', /does not delete anything/.test(await page.getByTestId('archive-confirm').innerText()) && (await page.getByTestId('archive-confirm-button').isDisabled()))
  await page.getByLabel(/^Reason/).fill('Closed for verification'); await page.getByTestId('archive-confirm-button').click(); await page.waitForSelector('[data-testid=rooms-flash]:has-text("archived")', { timeout: 15000 })
  await page.waitForFunction(() => [...document.querySelectorAll('table[aria-label=Rooms] tbody tr')].some((r) => r.textContent.includes('Verification Suite') && r.getAttribute('data-active') === 'false'), null, { timeout: 15000 })
  check('an archived room stays listed as ARCHIVED (never deleted) and can be restored', /ARCHIVED/.test(await suiteRow().innerText()) && (await suiteRow().getByRole('button', { name: 'Edit' }).count()) === 1)
  await suiteRow().getByRole('button', { name: 'Edit' }).click(); await page.waitForSelector('[data-testid=room-editor]')
  check('the editor of an archived room offers Restore', /Restore room/.test(await page.getByTestId('room-editor').innerText()))
  await page.getByTestId('room-archive').click(); await page.waitForSelector('[data-testid=room-error]')
  check('restoring without a reason is refused before anything is sent', /reason/i.test(await page.getByTestId('room-error').innerText()))
  await page.getByLabel(/^Reason/).fill('Reopened after verification'); await page.getByTestId('room-archive').click(); await page.waitForSelector('[data-testid=rooms-flash]:has-text("restored")', { timeout: 15000 })
  await page.waitForFunction(() => [...document.querySelectorAll('table[aria-label=Rooms] tbody tr')].some((r) => r.textContent.includes('Verification Suite') && r.getAttribute('data-active') === 'true'), null, { timeout: 15000 })
  check('a restored room is ACTIVE again', /ACTIVE/.test(await suiteRow().innerText()))
  check('child-age rules are shown read-only from contracts', (await page.getByTestId('child-age-rules').count()) === 1 && /contract policies, not room data/.test(await page.getByTestId('child-age-rules').innerText()))
  await openHotel(page, 'kilo', 'amenities'); await page.waitForSelector('[data-testid=amenities-form]')
  await page.getByLabel('Swimming pool', { exact: true }).check(); await page.getByLabel('Swimming pool fee').selectOption('PAID'); await page.getByLabel('Spa', { exact: true }).check()
  await page.getByTestId('amenities-save').click(); await page.waitForSelector('[data-testid=amenities-flash]:has-text("Amenities saved")', { timeout: 15000 })
  await page.reload(); await page.waitForSelector('[data-testid=amenities-form]')
  check('hotel amenities persist with an explicit fee type; an untouched one stays unrecorded', (await page.getByLabel('Swimming pool', { exact: true }).isChecked()) && (await page.getByLabel('Swimming pool fee').inputValue()) === 'PAID' && (await page.getByLabel('Spa fee').inputValue()) === 'UNKNOWN' && !(await page.getByLabel('Gym', { exact: false }).first().isChecked().catch(() => false)))
  check('room-only amenities are not offered at hotel level', (await page.getByLabel('Balcony', { exact: true }).count()) === 0)
  await openHotel(page, 'kilo', 'policies'); await page.waitForSelector('[data-testid=policies-form]')
  await page.getByLabel(/^Children/).fill('Children under 12 stay free in existing bedding.')
  await page.getByTestId('policies-save').click(); await page.waitForSelector('[data-testid=policies-flash]:has-text("Hotel policies saved")', { timeout: 15000 })
  await page.reload(); await page.waitForSelector('[data-testid=policies-form]')
  check('hotel policies persist and are kept apart from rate-specific cancellation terms', (await page.getByLabel(/^Children/).inputValue()).startsWith('Children under 12') && (await page.getByTestId('contract-terms').count()) === 1 && /never replaces them/.test(await page.getByTestId('contract-terms').innerText()))
  await openHotel(page, 'kilo', 'images'); await page.waitForSelector('[data-testid=hotel-images]'); await page.waitForSelector('[data-testid=images-empty]', { timeout: 15000 })
  check('Images shows an honest empty state with the real limits and an upload control (see verify-images.cjs for the full flow)', (await page.getByTestId('images-empty').count()) === 1 && /5 MB/.test(await text(page)) && (await page.locator('input[type=file]').count()) === 1)
  await page.goto(`${BASE}/hotels/${H.kilo}/rooms/new`); await page.waitForURL(/tab=rooms&room=new/, { timeout: 15000 }); await page.waitForSelector('[data-testid=room-editor]')
  check('the old Add room route forwards to the Rooms tab editor', /tab=rooms/.test(page.url()))

  // ---- Supplier mapping governance (ADR 0021, stage 3) ----
  await openHotel(page, 'alpha', 'mappings'); await page.waitForSelector('[data-testid=hotel-mappings] table')
  const alphaSupplierHotelId = (await page.locator('[data-testid=hotel-mappings] tbody tr code').first().innerText()).trim()
  await openHotel(page, 'kilo', 'mappings'); await page.waitForSelector('[data-testid=hotel-mapping-empty]')
  check('a hotel with no mapping says no supplier can sell it, and offers to add one', /no supplier can sell this hotel/.test(await text(page)) && (await page.getByRole('button', { name: 'Add supplier mapping' }).count()) === 1)
  await page.getByRole('button', { name: 'Add supplier mapping' }).click(); await page.waitForSelector('[data-testid=new-hotel-mapping]')
  await page.waitForFunction(() => document.querySelectorAll('[data-testid=new-hotel-mapping] select option').length > 1, null, { timeout: 15000 })
  await page.locator('[data-testid=new-hotel-mapping] select').selectOption({ label: 'Gulf Direct' }); await page.getByLabel('Supplier hotel id').fill(alphaSupplierHotelId)
  await page.getByRole('button', { name: 'Create mapping' }).click(); await page.waitForSelector('[data-testid=mapping-error]')
  const conflict = await page.getByTestId('mapping-error').innerText()
  check('a supplier hotel id already mapped to another hotel is refused and names that hotel', /already mapped for this supplier/.test(conflict) && /Atlantis Palm Resort/.test(conflict), conflict.slice(0, 120))
  await page.getByLabel('Supplier hotel id').fill(`KILO-SH-${Date.now()}`); await page.getByLabel('Source (optional)').fill('verification feed')
  await page.getByRole('button', { name: 'Create mapping' }).click(); await page.waitForSelector('[data-testid=mapping-flash]:has-text("PENDING REVIEW")', { timeout: 15000 })
  await page.waitForSelector('[data-testid=hotel-mappings] tbody tr[data-status=PENDING]')
  check('a new supplier mapping is PENDING REVIEW with its provenance and is not verified automatically', /PENDING REVIEW/.test(await page.locator('[data-testid=hotel-mappings] tbody tr').first().innerText()) && /verification feed/.test(await page.locator('[data-testid=hotel-mappings] tbody tr').first().innerText()))
  await page.getByRole('button', { name: 'Add supplier mapping' }).click(); await page.waitForSelector('[data-testid=new-hotel-mapping]')
  await page.waitForFunction(() => document.querySelectorAll('[data-testid=new-hotel-mapping] select option').length > 1, null, { timeout: 15000 })
  await page.locator('[data-testid=new-hotel-mapping] select').selectOption({ label: 'Gulf Direct' }); await page.getByLabel('Supplier hotel id').fill('SECOND-ID')
  await page.getByRole('button', { name: 'Create mapping' }).click(); await page.waitForSelector('[data-testid=mapping-error]')
  check('a second mapping from the same supplier to the same hotel is refused', /already has a mapping from this supplier/.test(await page.getByTestId('mapping-error').innerText()))
  const decisionRow = () => page.locator('[data-testid=hotel-mappings] tbody tr').first()
  await decisionRow().getByRole('button', { name: 'Approve hotel mapping' }).click()
  check('a decision cannot be confirmed without a reason', await page.getByRole('button', { name: 'Confirm approve' }).isDisabled())
  await page.getByLabel(/Reason for approving/).fill('Verified against the supplier contract'); await page.getByRole('button', { name: 'Confirm approve' }).click()
  await page.waitForSelector('[data-testid=mapping-flash]:has-text("verified")', { timeout: 15000 }); await page.waitForSelector('[data-testid=hotel-mappings] tbody tr[data-status=MAPPED]')
  check('after a person approves it, the mapping reads VERIFIED and only Reopen remains', /VERIFIED/.test(await decisionRow().innerText()) && (await decisionRow().getByRole('button', { name: 'Reopen hotel mapping' }).count()) === 1 && (await decisionRow().getByRole('button', { name: 'Approve hotel mapping' }).count()) === 0)
  await page.getByTestId('new-room-mapping').waitFor(); await page.getByLabel('Canonical room').selectOption({ index: 1 }); await page.getByLabel('Supplier room id').fill('KILO-ROOM-1')
  await page.getByRole('button', { name: 'Create room mapping' }).click(); await page.waitForSelector('[data-testid=mapping-flash]:has-text("Room mapping created")', { timeout: 15000 })
  await page.waitForSelector('[data-testid=room-mappings] tbody tr[data-status=PENDING]')
  await page.locator('[data-testid=room-mappings] tbody tr').first().getByRole('button', { name: 'Approve room mapping' }).click(); await page.getByLabel(/Reason for approving/).fill('Same bedding and occupancy'); await page.getByRole('button', { name: 'Confirm approve' }).click()
  await page.waitForSelector('[data-testid=room-mappings] tbody tr[data-status=MAPPED]', { timeout: 15000 })
  await page.waitForFunction(() => /Verified against the supplier contract/.test(document.querySelector('[data-testid=mapping-history]')?.textContent ?? ''), null, { timeout: 15000 })
  const hist = await page.getByTestId('mapping-history').innerText()
  check('the mapping history shows who decided, the status change, the reason and the request id', /PENDING → MAPPED/.test(hist) && /Verified against the supplier contract/.test(hist) && /supply\.hotel_mapping\.approved/.test(hist) && /supply\.room_mapping\.approved/.test(hist))
  check('board basis mapping is stated as not modelled', /Not modelled yet/.test(await page.getByTestId('board-note').innerText()))
  const viewerMap = await login(browser, seed.viewerEmail)
  await viewerMap.page.goto(`${BASE}/hotels/${H.alpha}?tab=mappings`); await viewerMap.page.waitForSelector('[data-state], [data-testid=hotel-mappings]', { timeout: 20000 })
  check('a read-only user sees mappings without decision or add controls', (await viewerMap.page.getByRole('button', { name: /Approve|Reject|Reopen|Add supplier mapping/ }).count()) === 0)
  await viewerMap.ctx.close()

  // ---- Quick Update (ADR 0021, stage 5): scope, opt-in panels, preview, review, apply, stale, atomic ----
  const dayIso = (offset) => new Date(new Date().toISOString().slice(0, 10) + 'T00:00:00.000Z').getTime() + offset * 86_400_000
  const ymd = (offset) => new Date(dayIso(offset)).toISOString().slice(0, 10)
  const openQuick = async (pg) => { await pg.goto(`${BASE}/hotels/${H.alpha}?tab=quick`); await pg.waitForSelector('[data-testid=quick-update] table[aria-label="Rate plans to update"]', { timeout: 20000 }) }
  const scopeAlpha = async (pg, from, to) => { await pg.locator('[data-testid=quick-update] tbody tr').first().getByRole('checkbox').check(); await pg.locator('[data-testid=quick-update] input[type=date]').nth(0).fill(from); await pg.locator('[data-testid=quick-update] input[type=date]').nth(1).fill(to) }
  await openQuick(page)
  check('Quick Update names the plan currency, offers no lock actions and points shared pools to Inventory & Allotment', /AED/.test(await page.getByTestId('quick-update').innerText()) && !/lock dates|apply & lock/i.test(await page.getByTestId('quick-update').innerText().then((t) => t.replace(/What Quick Update does not do[\s\S]*$/, ''))) && /Manage pools in Inventory/.test(await page.getByTestId('quick-update').innerText()))
  await scopeAlpha(page, ymd(6), ymd(10))
  check('nothing can be previewed until a panel is ticked and filled', await page.getByTestId('qu-preview').isDisabled())
  await page.getByLabel('Change price').check(); await page.getByLabel(/^Amount per night/).fill('456.78')
  check('untouched panels stay closed (availability and restrictions are not sent)', (await page.locator('[data-panel=availability] input[inputmode=numeric]').count()) === 0 && (await page.locator('[data-panel=restrictions] input[inputmode=numeric]').count()) === 0)
  await page.getByTestId('qu-preview').click(); await page.waitForSelector('[data-testid=qu-preview-result]')
  const quCounts = await page.getByTestId('qu-counts').innerText()
  check('the preview states the exact record count and what will change', /5 records over 5 nights/.test(quCounts) && /5 will change/.test(quCounts) && /0 invalid/.test(quCounts), quCounts.slice(0, 120))
  const firstRow = await page.locator('[data-testid=qu-preview-result] tbody tr').first().innerText()
  check('the preview shows old and new values with the currency, and unsupported operations', /price:/.test(firstRow) && /456\.78/.test(firstRow) && /→/.test(firstRow) && /Lock dates/.test(await page.getByTestId('qu-unsupported').textContent()) && /release deadline/.test(await page.getByTestId('qu-unsupported').textContent()))
  check('apply needs a reason', await page.getByTestId('qu-apply').isDisabled())
  await page.getByLabel(/Reason \(required/).fill('Verification rate review')
  await page.getByLabel(/^Amount per night/).fill('456.79')
  check('changing the form after a preview forces a new preview', (await page.getByTestId('qu-stale-form').count()) === 1 && (await page.getByTestId('qu-apply').isDisabled()))
  await page.getByTestId('qu-preview').click(); await page.waitForFunction(() => !document.querySelector('[data-testid=qu-stale-form]'), null, { timeout: 15000 })
  // a second person previews the same scope, then this person applies first
  const { ctx: q2, page: qp2 } = await login(browser, seed.ownerEmail)
  await openQuick(qp2); await scopeAlpha(qp2, ymd(6), ymd(10)); await qp2.getByLabel('Change price').check(); await qp2.getByLabel(/^Amount per night/).fill('500.00')
  await qp2.getByTestId('qu-preview').click(); await qp2.waitForSelector('[data-testid=qu-preview-result]'); await qp2.getByLabel(/Reason \(required/).fill('Second window')
  await page.getByLabel(/Reason \(required/).fill('Verification rate review'); await page.getByTestId('qu-apply').click(); await page.waitForSelector('[data-testid=qu-result]', { timeout: 20000 })
  const applied = await page.getByTestId('qu-result').innerText(); const auditRef = await page.getByTestId('qu-request-id').innerText()
  check('apply reports what was written and an audit reference', /Applied 5 records: 5 rates and 0 inventory rows and 0 pool nights written/.test(applied) && auditRef.length > 8, applied.slice(0, 100))
  await qp2.getByTestId('qu-apply').click(); await qp2.waitForSelector('[data-testid=qu-error]', { timeout: 15000 })
  check('a stale preview fails visibly and nothing is written', /changed after you previewed/i.test(await qp2.getByTestId('qu-error').innerText()))
  await q2.close()
  await openHotel(page, 'alpha', 'rates'); await page.waitForSelector('[data-testid=calendar]')
  const rowText = await page.locator(`[data-testid=calendar] tr[data-date="${ymd(6)}"]`).first().innerText()
  const outside = await page.locator(`[data-testid=calendar] tr[data-date="${ymd(11)}"]`).first().innerText()
  check('the Rates & Inventory view shows the persisted price on the selected dates only, with the stop-sell and allotment untouched', /456\.79/.test(rowText) && !/456\.79/.test(outside) && /No/.test(rowText))
  check('the audit trail records the same request id', await (async () => { await page.goto(`${BASE}/hotels/${H.alpha}?tab=audit`); await page.waitForSelector('table[aria-label="Hotel audit events"]'); return (await text(page)).includes(auditRef) && /hotel\.quick_update\.applied/.test(await text(page)) })())
  // an invalid record (a past date) makes the whole batch unappliable
  await openQuick(page); await scopeAlpha(page, ymd(-2), ymd(1)); await page.getByLabel('Change availability').check(); await page.getByLabel(/^Allotment/).fill('4')
  await page.getByTestId('qu-preview').click(); await page.waitForSelector('[data-testid=qu-preview-result]')
  check('a past date is invalid in the hotel time zone, and the batch cannot be applied', /before today in the hotel/.test(await page.getByTestId('qu-preview-result').innerText()) && /whole or not at all/.test(await page.getByTestId('qu-preview-result').innerText()))
  await page.getByLabel(/Reason \(required/).fill('Should not be possible'); check('apply stays disabled while any record is invalid', await page.getByTestId('qu-apply').isDisabled())
  const qv = await login(browser, seed.viewerEmail); await qv.page.goto(`${BASE}/hotels/${H.alpha}`); await qv.page.waitForSelector('[data-testid=hotel-header]', { timeout: 20000 })
  check('a user without rate or availability rights does not see the Quick Update tab', (await qv.page.getByRole('tab', { name: 'Quick Update' }).count()) === 0)
  await qv.ctx.close()

  // ---- Distribution & Readiness (ADR 0021, stage 6): publication, eligibility, transaction enablement and coverage are separate ----
  await openHotel(page, 'alpha', 'sellability'); await page.waitForSelector('[data-testid=dist-coverage]')
  const catalogueText = await page.getByTestId('dist-catalogue').innerText(); const txText = await page.getByTestId('dist-transaction').innerText()
  check('catalogue publication, distribution and transaction enablement are shown apart', /COMPLETE/.test(catalogueText) && /ELIGIBLE FOR THE CATALOGUE/.test(catalogueText) && (await page.getByTestId('dist-distribution').count()) === 1 && /BOOKING NOT ENABLED/.test(txText))
  check('the page says publishing never changes the booking switch and eligibility is not sellability', /never changes it/.test(txText) && /Eligibility is not sellability/.test(catalogueText))
  check('seven-day coverage states sellable plan-nights out of the total', /\d+ of \d+\s+plan-nights are sellable/.test(await page.getByTestId('dist-coverage-summary').innerText()) && /next 7 nights/.test(await page.getByTestId('dist-coverage').innerText()))
  await openHotel(page, 'foxtrot', 'sellability'); await page.waitForSelector('[data-testid=dist-coverage]')
  const fox = await page.getByTestId('dist-coverage').innerText()
  check('blockers are listed by reason with the dates, rooms, rate plans and suppliers affected', (await page.locator('[data-testid=dist-coverage] tr[data-reason]').count()) >= 1 && /Gulf Direct/.test(fox) && /Deluxe Sea View/.test(fox) && /Family Suite/.test(fox) && new RegExp(ymd(0)).test(fox) && /0 of \d+\s+plan-nights are sellable/.test(fox))
  check('a hotel with nothing sellable is not shown as sellable to Agents', /NOT SELLABLE TO AGENTS/.test(await page.getByTestId('dist-distribution').innerText()))
  await openHotel(page, 'kilo', 'sellability'); await page.waitForSelector('[data-testid=dist-coverage]')
  check('a hotel with no rate plan says there is nothing to assess', /no rate plan, so there is nothing to assess/.test(await page.getByTestId('dist-coverage').innerText()))
  check('the stay evaluator remains available and read-only', (await page.getByRole('button', { name: 'Check sellability' }).count()) === 1 && /creates no hold and no booking/.test(await text(page)))

  // ---- directory: search by canonical id and external id, filters persist in the URL ----
  await page.goto(`${BASE}/hotels`); await page.waitForSelector('[data-testid=hotels-table]')
  await page.getByLabel('Search hotels').fill('GV-'); await page.getByLabel('Search hotels').press('Enter'); await page.waitForFunction(() => location.search.includes('search=GV-'))
  await page.waitForFunction(() => document.querySelectorAll('[data-testid=hotels-table] tbody tr').length === 1, null, { timeout: 15000 })
  check('searching an external identifier finds exactly the hotel it belongs to', (await page.locator('[data-testid=hotel-canonical-id]').first().innerText()).trim() === H.kilo)
  await page.goto(`${BASE}/hotels?search=${H.alpha}`); await page.waitForSelector('[data-testid=hotels-table]')
  check('searching a canonical id finds that hotel', (await rows(page)) === 1 && (await page.locator('[data-testid=hotel-canonical-id]').first().innerText()).trim() === H.alpha)
  await page.goto(`${BASE}/hotels?stars=UNRATED`); await page.waitForSelector('[data-testid=hotels-table], [data-state]')
  check('the unrated star filter is URL-persisted and applied by the server', /stars=UNRATED/.test(page.url()) && (await page.locator('[data-testid=hotels-table] tbody tr td:nth-child(4)').allInnerTexts()).every((t) => /Unrated/.test(t)))

  // ---- read-only people and other tenants ----
  const { ctx: vctx, page: vpage } = await login(browser, seed.viewerEmail)
  await vpage.goto(`${BASE}/hotels/${H.alpha}?tab=setup`); await vpage.waitForSelector('[data-testid=setup-form]', { timeout: 20000 })
  const patched = await vpage.evaluate(async ([id, tenant]) => (await fetch(`/api/v1/admin/hotels/${id}/setup`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json', 'x-fbeds-tenant-id': tenant }, body: JSON.stringify({ idempotencyKey: 'viewer-attempt-1', expectedToken: 'x', area: 'Nope' }) })).status, [H.alpha, seed.tenantA])
  check('a read-only user sees no save control and no private contacts, and the API refuses the mutation', (await vpage.getByTestId('setup-save').count()) === 0 && (await vpage.getByTestId('contacts-hidden').count()) === 1 && patched === 403, `status=${patched}`)
  await vctx.close()
  const crossTenant = await page.evaluate(async ([id, tenant]) => (await fetch(`/api/v1/admin/hotels/${id}/setup`, { credentials: 'include', headers: { 'x-fbeds-tenant-id': tenant } })).status, [H.oscar, seed.tenantA])
  check("another tenant's hotel setup is not readable", crossTenant === 404, `status=${crossTenant}`)

  // ---- keyboard, responsive, accessibility ----------------------------------------------------------------------------------------
  await openHotel(page, 'alpha'); await page.locator('[role=tab]').first().focus(); await page.keyboard.press('Tab')
  const focusedRole = await page.evaluate(() => document.activeElement?.getAttribute('role'))
  await page.getByRole('tab', { name: 'Rooms' }).focus(); await page.keyboard.press('Enter'); await page.waitForURL(/tab=rooms/)
  check('tabs are keyboard reachable and activate with Enter', focusedRole === 'tab' && /tab=rooms/.test(page.url()))
  for (const [w, h] of [[1280, 900], [768, 900], [390, 800]]) {
    await page.setViewportSize({ width: w, height: h })
    for (const url of [`${BASE}/hotels`, `${BASE}/hotels/${H.alpha}?tab=rates`, `${BASE}/hotels/${H.alpha}?tab=setup`, `${BASE}/hotels/${H.alpha}?tab=rooms`, `${BASE}/hotels/${H.alpha}?tab=policies`, `${BASE}/exceptions`]) {
      await page.goto(url); await page.waitForSelector('table, [data-state], [data-testid=setup-form], [data-testid=policies-form]'); await page.waitForTimeout(500)
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
      const focusable = await page.evaluate(() => [...document.querySelectorAll('[role=region][aria-label]')].every((r) => r.scrollWidth <= r.clientWidth + 1 || r.getAttribute('tabindex') === '0'))
      check(`no page-level horizontal overflow at ${w}px on ${new URL(url).pathname}${new URL(url).search}`, overflow <= 1 && focusable, `overflow=${overflow}`)
    }
  }
  await page.setViewportSize({ width: 1280, height: 900 })
  await openHotel(page, 'bravo', 'sellability'); await page.getByRole('button', { name: 'Check sellability' }).click(); await page.waitForSelector('[data-testid=sellability-result]')
  for (const [label, url, wait] of [['Hotels list', `${BASE}/hotels`, '[data-testid=hotels-table]'], ['Hotel 360', `${BASE}/hotels/${H.alpha}`, '[data-testid=readiness-gates]'], ['Rate & Inventory', `${BASE}/hotels/${H.bravo}?tab=rates`, '[data-testid=calendar]'], ['Hotel Setup', `${BASE}/hotels/${H.alpha}?tab=setup`, '[data-testid=setup-form]'], ['Distribution & Readiness', `${BASE}/hotels/${H.alpha}?tab=sellability`, '[data-testid=dist-coverage]'], ['Quick Update', `${BASE}/hotels/${H.alpha}?tab=quick`, '[data-testid=quick-update]'], ['Supplier Mapping', `${BASE}/hotels/${H.alpha}?tab=mappings`, '[data-testid=hotel-mappings]'], ['Rooms', `${BASE}/hotels/${H.alpha}?tab=rooms`, 'table[aria-label=Rooms]'], ['Amenities', `${BASE}/hotels/${H.alpha}?tab=amenities`, '[data-testid=amenities-form]'], ['Policies', `${BASE}/hotels/${H.alpha}?tab=policies`, '[data-testid=policies-form]'], ['Images', `${BASE}/hotels/${H.alpha}?tab=images`, '[data-testid=hotel-images]'], ['Sellability Inspector', null, '[data-testid=sellability-result]'], ['Exceptions', `${BASE}/exceptions`, '[data-testid=exceptions-table]']]) {
    if (url) { await page.goto(url); await page.waitForSelector(wait) }
    const axe = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
    const bad = axe.violations.filter((v) => ['serious', 'critical'].includes(v.impact))
    check(`axe ${label}: no serious/critical violations`, bad.length === 0, bad.map((v) => `${v.id}(${v.nodes.length}): ${v.nodes[0].target.join(' ').slice(0, 60)}`).join(' | '))
  }
  check('no uncaught page errors', errors.length === 0, errors.join(' | '))
  await ctx.close()

  // ---- permissions and tenants -------------------------------------------------------------------------------------------------
  const v = await login(browser, seed.viewerEmail)
  await v.page.goto(`${BASE}/hotels`); await v.page.waitForSelector('[data-testid=hotels-table]')
  check('viewer (supply.hotels.read only) can use the list', (await rows(v.page)) === 25)
  await openHotel(v.page, 'alpha'); await v.page.waitForTimeout(1200)
  const tabNames = await v.page.locator('[role=tab]').allInnerTexts()
  check('viewer: tabs needing other permissions are hidden', !tabNames.some((t) => /Contracts|Mappings|Rates|Sellability|Audit|Bookings/.test(t)), tabNames.join(','))
  await v.page.goto(`${BASE}/hotels/${H.alpha}?tab=contracts`); await v.page.waitForSelector('[data-state]', { timeout: 15000 })
  check('viewer deep-linking to Contracts gets FORBIDDEN, not an empty tab', (await stateOf(v.page)) === 'forbidden')
  await v.ctx.close()
  const b = await login(browser, seed.bownerEmail)
  await b.page.goto(`${BASE}/hotels`); await b.page.waitForSelector('[data-testid=hotels-table]')
  check('tenant B sees only its own hotel', (await rows(b.page)) === 1 && /Other Tenant Hotel/.test(await text(b.page)) && !/Atlantis/.test(await text(b.page)))
  await b.page.goto(`${BASE}/hotels/${H.alpha}`); await b.page.waitForSelector('[data-state]', { timeout: 15000 })
  check("tenant B opening tenant A's hotel gets not-found", (await stateOf(b.page)) === 'not-found')
  await b.page.goto(`${BASE}/exceptions`); await b.page.waitForSelector('[data-testid=exceptions-table], [data-state]')
  check('tenant B exceptions never mention tenant A hotels', !/Atlantis|Burj|Creek/.test(await text(b.page)))
  await b.ctx.close()

  await browser.close()
  const failed = results.filter((r) => !r.ok)
  console.log(`\n${results.length - failed.length}/${results.length} checks passed`)
  process.exit(failed.length ? 1 : 0)
})().catch((e) => { console.error(e); process.exit(2) })
