-- Hotel profile and external identifiers (ADR 0021). Descriptive and operational hotel content that "Hotel" does not hold:
-- legal name, chain and brand, area, postal code, descriptions, languages, check-in and check-out times, operational notes,
-- private contacts, hotel-level policies, classification and approval metadata, and external identifiers such as GIATA.
-- Nothing here is commercial: no rate, inventory, price or booking state, and no new lifecycle enum (Hotel.contentStatus stays
-- the profile approval state).
--
-- Integrity beyond Prisma: time format (HH:MM, 24h), text lengths, version >= 1, bounded language list, identifier format.
-- Optimistic concurrency uses "version". Actor ids are plain text without foreign keys so history survives user removal.
-- Contacts are private; no Agent, Website or supplier API reads "HotelProfile".
--
-- Tenant indexes: tenant_id leads every non-unique index; "hotel_id" is unique on "HotelProfile".
--
-- The conditional GRANTs mirror earlier migrations (ADR 0013): they are production privilege changes in effect and need the
-- human decision before this migration is applied to any persistent environment. Without them the API reports the setup as
-- unavailable and never as empty.
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP TABLE IF EXISTS "HotelExternalIdentifier", "HotelProfile";

-- CreateTable
CREATE TABLE "HotelProfile" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "legal_name" TEXT,
    "chain_name" TEXT,
    "brand_name" TEXT,
    "area" TEXT,
    "postal_code" TEXT,
    "short_description" TEXT,
    "full_description" TEXT,
    "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "check_in_time" CHAR(5),
    "check_out_time" CHAR(5),
    "operational_notes" TEXT,
    "contacts" JSONB NOT NULL DEFAULT '{}',
    "policies" JSONB NOT NULL DEFAULT '{}',
    "source_system" TEXT,
    "owner_user_id" TEXT,
    "star_source" TEXT,
    "star_verified_at" TIMESTAMP(3),
    "star_verified_by_id" TEXT,
    "approved_by_id" TEXT,
    "approved_at" TIMESTAMP(3),
    "version" INTEGER NOT NULL DEFAULT 1,
    "updated_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HotelProfile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HotelExternalIdentifier" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "hotel_id" TEXT NOT NULL,
    "scheme" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "created_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "HotelExternalIdentifier_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "HotelProfile_hotel_id_key" ON "HotelProfile"("hotel_id");

-- CreateIndex
CREATE INDEX "HotelProfile_tenant_id_hotel_id_idx" ON "HotelProfile"("tenant_id", "hotel_id");

-- CreateIndex
CREATE UNIQUE INDEX "HotelExternalIdentifier_tenant_id_scheme_value_key" ON "HotelExternalIdentifier"("tenant_id", "scheme", "value");

-- CreateIndex
CREATE UNIQUE INDEX "HotelExternalIdentifier_hotel_id_scheme_key" ON "HotelExternalIdentifier"("hotel_id", "scheme");

-- CreateIndex
CREATE INDEX "HotelExternalIdentifier_tenant_id_hotel_id_idx" ON "HotelExternalIdentifier"("tenant_id", "hotel_id");

-- AddForeignKey
ALTER TABLE "HotelProfile" ADD CONSTRAINT "HotelProfile_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HotelProfile" ADD CONSTRAINT "HotelProfile_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HotelExternalIdentifier" ADD CONSTRAINT "HotelExternalIdentifier_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HotelExternalIdentifier" ADD CONSTRAINT "HotelExternalIdentifier_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Integrity constraints
ALTER TABLE "HotelProfile" ADD CONSTRAINT "HotelProfile_version_positive" CHECK ("version" >= 1),
  ADD CONSTRAINT "HotelProfile_time_format" CHECK (
    ("check_in_time" IS NULL OR "check_in_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
    AND ("check_out_time" IS NULL OR "check_out_time" ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  ),
  ADD CONSTRAINT "HotelProfile_text_length" CHECK (
    ("legal_name" IS NULL OR char_length("legal_name") <= 200)
    AND ("chain_name" IS NULL OR char_length("chain_name") <= 120)
    AND ("brand_name" IS NULL OR char_length("brand_name") <= 120)
    AND ("area" IS NULL OR char_length("area") <= 120)
    AND ("postal_code" IS NULL OR char_length("postal_code") <= 20)
    AND ("short_description" IS NULL OR char_length("short_description") <= 500)
    AND ("full_description" IS NULL OR char_length("full_description") <= 4000)
    AND ("operational_notes" IS NULL OR char_length("operational_notes") <= 2000)
    AND ("source_system" IS NULL OR char_length("source_system") <= 80)
    AND ("star_source" IS NULL OR char_length("star_source") <= 120)
  ),
  ADD CONSTRAINT "HotelProfile_languages_bounded" CHECK (cardinality("languages") <= 20),
  ADD CONSTRAINT "HotelProfile_json_objects" CHECK (jsonb_typeof("contacts") = 'object' AND jsonb_typeof("policies") = 'object'),
  ADD CONSTRAINT "HotelProfile_star_verification_complete" CHECK (("star_verified_at" IS NULL) = ("star_verified_by_id" IS NULL)),
  ADD CONSTRAINT "HotelProfile_approval_complete" CHECK (("approved_at" IS NULL) = ("approved_by_id" IS NULL));

ALTER TABLE "HotelExternalIdentifier" ADD CONSTRAINT "HotelExternalIdentifier_format" CHECK (
    "scheme" ~ '^[A-Z][A-Z0-9_]{1,31}$' AND char_length("value") BETWEEN 1 AND 80 AND "value" = btrim("value")
  );

-- Row-level security: tenant isolation on both tables.
ALTER TABLE "HotelProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HotelProfile" FORCE ROW LEVEL SECURITY;
CREATE POLICY "HotelProfile_tenant_isolation" ON "HotelProfile" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "HotelExternalIdentifier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HotelExternalIdentifier" FORCE ROW LEVEL SECURITY;
CREATE POLICY "HotelExternalIdentifier_tenant_isolation" ON "HotelExternalIdentifier" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "HotelProfile" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "HotelExternalIdentifier" TO fbeds_api';
  END IF;
END $$;
