-- Clients, Service and Distribution (ADR 0019): agencies and their members, support cases with append-only notes,
-- and per-agency distribution restrictions. Record-keeping and exposure control only: nothing here moves money, sets a
-- credit limit or changes a booking.
--
-- Integrity beyond Prisma: code and country format, case status and timestamp consistency, restriction scope-target consistency,
-- and a partial unique index so at most one ACTIVE restriction exists per (agency, scope, target). A user belongs to at most one
-- agency per tenant. Case notes are append-only: the API role is granted INSERT and SELECT only on them.
-- Prisma cannot model the partial unique index, so `prisma migrate diff` lists it like the pgvector index.
--
-- Also seeds the six permission keys these APIs enforce (agency.read/manage, case.read/manage, distribution.read/manage) into the
-- global "Permission" table so roles can be granted them. Nothing is granted to any role by this migration.
--
-- Tenant indexes: every table is indexed by tenant_id first; see the CREATE INDEX statements.
--
-- The conditional GRANTs mirror "SupplierMutation". They are production privilege changes in effect, so they need the ADR 0013
-- human decision before this migration is applied to any persistent environment. Distribution restrictions are enforced in Agent
-- search for members of an agency; if the API role cannot read them, those members get no results (fail closed).
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP TABLE IF EXISTS "DistributionRestriction", "ServiceCaseNote", "ServiceCase", "AgencyMember", "Agency";
--   DROP TYPE IF EXISTS "DistributionRestrictionStatus", "DistributionScope", "ServiceCaseStatus", "ServiceCasePriority", "ServiceCaseCategory", "AgencyStatus";
--   DELETE FROM "Permission" WHERE key IN ('agency.read','agency.manage','case.read','case.manage','distribution.read','distribution.manage');

-- CreateEnum
CREATE TYPE "AgencyStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "ServiceCaseCategory" AS ENUM ('BOOKING', 'HOTEL', 'SUPPLIER', 'AGENCY', 'OTHER');

-- CreateEnum
CREATE TYPE "ServiceCasePriority" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT');

-- CreateEnum
CREATE TYPE "ServiceCaseStatus" AS ENUM ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');

-- CreateEnum
CREATE TYPE "DistributionScope" AS ENUM ('HOTEL', 'SUPPLIER');

-- CreateEnum
CREATE TYPE "DistributionRestrictionStatus" AS ENUM ('ACTIVE', 'RETIRED');


-- CreateTable
CREATE TABLE "Agency" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "country_code" CHAR(2),
    "status" "AgencyStatus" NOT NULL DEFAULT 'ACTIVE',
    "notes" TEXT,
    "created_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Agency_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgencyMember" (
    "agency_id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AgencyMember_pkey" PRIMARY KEY ("agency_id","user_id")
);

-- CreateTable
CREATE TABLE "ServiceCase" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "reference" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" "ServiceCaseCategory" NOT NULL,
    "priority" "ServiceCasePriority" NOT NULL DEFAULT 'NORMAL',
    "status" "ServiceCaseStatus" NOT NULL DEFAULT 'OPEN',
    "booking_id" TEXT,
    "hotel_id" TEXT,
    "supplier_id" TEXT,
    "agency_id" TEXT,
    "opened_by_id" TEXT NOT NULL,
    "assignee_id" TEXT,
    "resolved_at" TIMESTAMP(3),
    "closed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ServiceCase_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ServiceCaseNote" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "case_id" TEXT NOT NULL,
    "author_id" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ServiceCaseNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DistributionRestriction" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "agency_id" TEXT NOT NULL,
    "scope" "DistributionScope" NOT NULL,
    "hotel_id" TEXT,
    "supplier_id" TEXT,
    "status" "DistributionRestrictionStatus" NOT NULL DEFAULT 'ACTIVE',
    "reason" TEXT NOT NULL,
    "created_by_id" TEXT NOT NULL,
    "retired_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DistributionRestriction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Agency_tenant_id_status_idx" ON "Agency"("tenant_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "Agency_tenant_id_code_key" ON "Agency"("tenant_id", "code");

-- CreateIndex
CREATE INDEX "AgencyMember_tenant_id_agency_id_idx" ON "AgencyMember"("tenant_id", "agency_id");

-- CreateIndex
CREATE UNIQUE INDEX "AgencyMember_tenant_id_user_id_key" ON "AgencyMember"("tenant_id", "user_id");

-- CreateIndex
CREATE INDEX "ServiceCase_tenant_id_status_idx" ON "ServiceCase"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "ServiceCase_tenant_id_assignee_id_status_idx" ON "ServiceCase"("tenant_id", "assignee_id", "status");

-- CreateIndex
CREATE INDEX "ServiceCase_tenant_id_booking_id_idx" ON "ServiceCase"("tenant_id", "booking_id");

-- CreateIndex
CREATE UNIQUE INDEX "ServiceCase_tenant_id_reference_key" ON "ServiceCase"("tenant_id", "reference");

-- CreateIndex
CREATE INDEX "ServiceCaseNote_tenant_id_case_id_created_at_idx" ON "ServiceCaseNote"("tenant_id", "case_id", "created_at");

-- CreateIndex
CREATE INDEX "DistributionRestriction_tenant_id_status_idx" ON "DistributionRestriction"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "DistributionRestriction_tenant_id_agency_id_status_idx" ON "DistributionRestriction"("tenant_id", "agency_id", "status");

-- AddForeignKey
ALTER TABLE "Agency" ADD CONSTRAINT "Agency_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Agency" ADD CONSTRAINT "Agency_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgencyMember" ADD CONSTRAINT "AgencyMember_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "Agency"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgencyMember" ADD CONSTRAINT "AgencyMember_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AgencyMember" ADD CONSTRAINT "AgencyMember_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "Agency"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_opened_by_id_fkey" FOREIGN KEY ("opened_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCaseNote" ADD CONSTRAINT "ServiceCaseNote_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCaseNote" ADD CONSTRAINT "ServiceCaseNote_case_id_fkey" FOREIGN KEY ("case_id") REFERENCES "ServiceCase"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ServiceCaseNote" ADD CONSTRAINT "ServiceCaseNote_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "Agency"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Integrity constraints
ALTER TABLE "Agency" ADD CONSTRAINT "Agency_code_format" CHECK ("code" ~ '^[A-Z0-9][A-Z0-9-]{0,38}[A-Z0-9]$'),
  ADD CONSTRAINT "Agency_country_format" CHECK ("country_code" IS NULL OR "country_code" ~ '^[A-Z]{2}$'),
  ADD CONSTRAINT "Agency_name_length" CHECK (char_length("name") BETWEEN 1 AND 120),
  ADD CONSTRAINT "Agency_notes_length" CHECK ("notes" IS NULL OR char_length("notes") <= 1000);

ALTER TABLE "ServiceCase" ADD CONSTRAINT "ServiceCase_text_length" CHECK (char_length("subject") BETWEEN 1 AND 200 AND char_length("description") BETWEEN 1 AND 2000),
  ADD CONSTRAINT "ServiceCase_status_timestamps" CHECK (
    ("status" IN ('OPEN', 'IN_PROGRESS') AND "closed_at" IS NULL AND "resolved_at" IS NULL)
    OR ("status" = 'RESOLVED' AND "resolved_at" IS NOT NULL AND "closed_at" IS NULL)
    OR ("status" = 'CLOSED' AND "closed_at" IS NOT NULL)
  );

ALTER TABLE "ServiceCaseNote" ADD CONSTRAINT "ServiceCaseNote_body_length" CHECK (char_length("body") BETWEEN 1 AND 2000);

ALTER TABLE "DistributionRestriction" ADD CONSTRAINT "DistributionRestriction_scope_target" CHECK (
    ("scope" = 'HOTEL' AND "hotel_id" IS NOT NULL AND "supplier_id" IS NULL)
    OR ("scope" = 'SUPPLIER' AND "supplier_id" IS NOT NULL AND "hotel_id" IS NULL)
  ),
  ADD CONSTRAINT "DistributionRestriction_status_timestamps" CHECK (
    ("status" = 'ACTIVE' AND "retired_at" IS NULL) OR ("status" = 'RETIRED' AND "retired_at" IS NOT NULL)
  );

-- At most one ACTIVE restriction per agency and target.
CREATE UNIQUE INDEX "DistributionRestriction_one_active_per_target" ON "DistributionRestriction"("tenant_id", "agency_id", "scope", COALESCE("hotel_id", ''), COALESCE("supplier_id", '')) WHERE "status" = 'ACTIVE';

-- Row-level security: tenant isolation on every table.
ALTER TABLE "Agency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Agency" FORCE ROW LEVEL SECURITY;
CREATE POLICY "Agency_tenant_isolation" ON "Agency" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "AgencyMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgencyMember" FORCE ROW LEVEL SECURITY;
CREATE POLICY "AgencyMember_tenant_isolation" ON "AgencyMember" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "ServiceCase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceCase" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ServiceCase_tenant_isolation" ON "ServiceCase" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "ServiceCaseNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ServiceCaseNote" FORCE ROW LEVEL SECURITY;
CREATE POLICY "ServiceCaseNote_tenant_isolation" ON "ServiceCaseNote" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());
ALTER TABLE "DistributionRestriction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DistributionRestriction" FORCE ROW LEVEL SECURITY;
CREATE POLICY "DistributionRestriction_tenant_isolation" ON "DistributionRestriction" USING ("tenant_id" = "fbeds_current_tenant_id"()) WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

-- Permission keys enforced by the new APIs. Granted to no role here.
INSERT INTO "Permission" ("id", "key", "description") VALUES
  (gen_random_uuid()::text, 'agency.read', 'View agencies and their members'),
  (gen_random_uuid()::text, 'agency.manage', 'Create and edit agencies and manage their members'),
  (gen_random_uuid()::text, 'case.read', 'View service cases'),
  (gen_random_uuid()::text, 'case.manage', 'Open, assign, update and add notes to service cases'),
  (gen_random_uuid()::text, 'distribution.read', 'View distribution restrictions'),
  (gen_random_uuid()::text, 'distribution.manage', 'Create and retire distribution restrictions')
ON CONFLICT ("key") DO NOTHING;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "Agency" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, DELETE ON "AgencyMember" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "ServiceCase" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT ON "ServiceCaseNote" TO fbeds_api';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "DistributionRestriction" TO fbeds_api';
  END IF;
END $$;
