-- Percent markup rules for NET daily rates (ADR 0018).
-- Rules are immutable except for status: DRAFT -> ACTIVE (only through an approved maker-checker request),
-- ACTIVE or DRAFT -> RETIRED. At most one ACTIVE rule exists per (tenant, scope, supplier, hotel); that is a
-- partial unique index, which Prisma cannot model, so `prisma migrate diff` will list it like the pgvector HNSW index.
-- basis_points is an integer 0..10000. Scope and target must agree. Money is never stored as a float.
--
-- Tenant indexes: (tenant_id, status) for the rule list and rule resolution, (tenant_id, scope, supplier_id, hotel_id) for lookups.
--
-- The conditional GRANT below mirrors "SupplierMutation" and "ApprovalRequest". It is a production privilege change in
-- effect, so it needs the ADR 0013 human decision before this migration is applied to any persistent environment.
-- Rule resolution by the Agent search needs SELECT for the API runtime role, so that grant is part of the same decision.
--
-- Rollback is a later forward migration. Do not edit this file after it is applied.
--   DROP POLICY IF EXISTS "CommercialMarkupRule_tenant_isolation" ON "CommercialMarkupRule";
--   DROP TABLE IF EXISTS "CommercialMarkupRule";
--   DROP TYPE IF EXISTS "MarkupRuleStatus";
--   DROP TYPE IF EXISTS "MarkupScope";

-- CreateEnum
CREATE TYPE "MarkupScope" AS ENUM ('TENANT_DEFAULT', 'SUPPLIER', 'HOTEL');

-- CreateEnum
CREATE TYPE "MarkupRuleStatus" AS ENUM ('DRAFT', 'ACTIVE', 'RETIRED');

-- CreateTable
CREATE TABLE "CommercialMarkupRule" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "scope" "MarkupScope" NOT NULL,
    "supplier_id" TEXT,
    "hotel_id" TEXT,
    "basis_points" INTEGER NOT NULL,
    "valid_from" DATE NOT NULL,
    "valid_to" DATE,
    "status" "MarkupRuleStatus" NOT NULL DEFAULT 'DRAFT',
    "reason" TEXT NOT NULL,
    "created_by_id" TEXT NOT NULL,
    "activated_at" TIMESTAMP(3),
    "retired_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CommercialMarkupRule_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "CommercialMarkupRule_basis_points_range" CHECK ("basis_points" >= 0 AND "basis_points" <= 10000),
    CONSTRAINT "CommercialMarkupRule_validity_order" CHECK ("valid_to" IS NULL OR "valid_to" >= "valid_from"),
    CONSTRAINT "CommercialMarkupRule_scope_target" CHECK (
      ("scope" = 'TENANT_DEFAULT' AND "supplier_id" IS NULL AND "hotel_id" IS NULL)
      OR ("scope" = 'SUPPLIER' AND "supplier_id" IS NOT NULL AND "hotel_id" IS NULL)
      OR ("scope" = 'HOTEL' AND "hotel_id" IS NOT NULL AND "supplier_id" IS NULL)
    ),
    CONSTRAINT "CommercialMarkupRule_status_timestamps" CHECK (
      ("status" = 'DRAFT' AND "activated_at" IS NULL AND "retired_at" IS NULL)
      OR ("status" = 'ACTIVE' AND "activated_at" IS NOT NULL AND "retired_at" IS NULL)
      OR ("status" = 'RETIRED' AND "retired_at" IS NOT NULL)
    )
);

-- CreateIndex
CREATE INDEX "CommercialMarkupRule_tenant_id_status_idx" ON "CommercialMarkupRule"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "CommercialMarkupRule_tenant_id_scope_supplier_id_hotel_id_idx" ON "CommercialMarkupRule"("tenant_id", "scope", "supplier_id", "hotel_id");

-- At most one ACTIVE rule per target.
CREATE UNIQUE INDEX "CommercialMarkupRule_one_active_per_target" ON "CommercialMarkupRule"("tenant_id", "scope", COALESCE("supplier_id", ''), COALESCE("hotel_id", '')) WHERE "status" = 'ACTIVE';

-- AddForeignKey
ALTER TABLE "CommercialMarkupRule" ADD CONSTRAINT "CommercialMarkupRule_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommercialMarkupRule" ADD CONSTRAINT "CommercialMarkupRule_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommercialMarkupRule" ADD CONSTRAINT "CommercialMarkupRule_hotel_id_fkey" FOREIGN KEY ("hotel_id") REFERENCES "Hotel"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CommercialMarkupRule" ADD CONSTRAINT "CommercialMarkupRule_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "CommercialMarkupRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CommercialMarkupRule" FORCE ROW LEVEL SECURITY;
CREATE POLICY "CommercialMarkupRule_tenant_isolation" ON "CommercialMarkupRule"
  USING ("tenant_id" = "fbeds_current_tenant_id"())
  WITH CHECK ("tenant_id" = "fbeds_current_tenant_id"());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fbeds_api') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE ON "CommercialMarkupRule" TO fbeds_api';
  END IF;
END $$;
