'use client'
import { useActionState, useEffect, useRef, useState } from 'react'
import { CircleAlert, CircleCheck, LoaderCircle, Mail } from 'lucide-react'
import { submitDemoRequest, initialDemoFormState } from '../../app/request-demo/actions'
import { trackWebsiteEvent } from '../../lib/analytics'
import { businessTypes, interestAreas, volumeOptions, type LeadField } from '../../lib/leads/validation'
export function DemoRequestForm({ contactEmail }: { contactEmail: string }) {
  const [state, action, pending] = useActionState(submitDemoRequest, initialDemoFormState)
  const [started, setStarted] = useState(false); const summary = useRef<HTMLDivElement>(null)
  useEffect(() => { if (state.status !== 'idle') summary.current?.focus(); if (state.status === 'invalid') trackWebsiteEvent('demo_form_validation_failed'); if (state.status === 'success') trackWebsiteEvent('demo_submission_succeeded') }, [state])
  const start = () => { if (!started) { setStarted(true); trackWebsiteEvent('demo_form_started') } }
  const field = (name: LeadField, label: string, type = 'text') => <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} required aria-invalid={Boolean(state.errors[name])} aria-describedby={state.errors[name] ? `${name}-error` : undefined} />{state.errors[name] && <p id={`${name}-error`} className="field-error">{state.errors[name]}</p>}</div>
  if (state.status === 'success') return <div className="form-success" role="status" tabIndex={-1} ref={summary}><CircleCheck aria-hidden="true" /><h2>Thank you. Your enquiry was accepted.</h2><p>Our team can now review the business context you provided.</p>{state.message && <p>{state.message}</p>}</div>
  return <form action={action} className="demo-form" noValidate onFocus={start} onSubmit={() => trackWebsiteEvent('demo_submission_attempted')}>
    {state.status !== 'idle' && <div ref={summary} tabIndex={-1} role="alert" className={`form-summary ${state.status === 'not_configured' ? 'form-notice' : ''}`}><CircleAlert aria-hidden="true" /><div><h2>{state.status === 'invalid' ? 'Check the highlighted fields' : 'Online submission was not completed'}</h2><p>{state.message ?? state.errors.form ?? 'Correct the errors below and try again.'}</p></div></div>}
    <div className="form-grid">{field('fullName', 'Full name')}{field('businessEmail', 'Business email', 'email')}{field('company', 'Company')}{field('market', 'Country or primary market')}<SelectField name="businessType" label="Business type" options={businessTypes} error={state.errors.businessType} /><SelectField name="monthlyVolume" label="Estimated monthly hotel bookings or distribution volume" options={volumeOptions} error={state.errors.monthlyVolume} /><SelectField name="interestArea" label="Area of interest" options={interestAreas} error={state.errors.interestArea} wide />
      <div className="field field-wide"><label htmlFor="message">What would you like to discuss?</label><p id="message-help" className="field-help">Include your current model, intended markets and integration needs. Do not include passwords or sensitive credentials.</p><textarea id="message" name="message" rows={6} required minLength={20} maxLength={2000} aria-invalid={Boolean(state.errors.message)} aria-describedby={`message-help${state.errors.message ? ' message-error' : ''}`} />{state.errors.message && <p id="message-error" className="field-error">{state.errors.message}</p>}</div>
      <div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off" /></div>
      <div className="field-wide consent"><input id="consent" name="consent" type="checkbox" aria-invalid={Boolean(state.errors.consent)} aria-describedby={state.errors.consent ? 'consent-error' : undefined} /><label htmlFor="consent">I agree that fBeds may use these details to respond to this enquiry.</label>{state.errors.consent && <p id="consent-error" className="field-error">{state.errors.consent}</p>}</div>
    </div><button className="button button-primary submit-button" type="submit" disabled={pending}>{pending ? <><LoaderCircle className="spinner" aria-hidden="true" /> Sending…</> : 'Send demo enquiry'}</button><p className="form-alternative"><Mail aria-hidden="true" /> Online submission not available? Email <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.</p>
  </form>
}
function SelectField({ name, label, options, error, wide }: { name: LeadField; label: string; options: readonly string[]; error?: string; wide?: boolean }) { return <div className={`field${wide ? ' field-wide' : ''}`}><label htmlFor={name}>{label}</label><select id={name} name={name} defaultValue="" required aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined}><option value="" disabled>Select an option</option>{options.map((option) => <option key={option}>{option}</option>)}</select>{error && <p id={`${name}-error`} className="field-error">{error}</p>}</div> }
